### ISSUE TITLE
feature: Upgrading from rocksdb-4.13 to rocksdb-6.12.6 failed initialization

### ISSUE THREAD

**Issue by lylth** [stoneatom/stonedb#10]
**Is your feature request related to a problem? Please describe.**

Upgrading from rocksdb-4.13 to rocksdb-6.12.6 failed initialization
Error executing reinstall.sh script
```
stonedb56/install/bin/mysqld: Error opening rocks instance. status msg: Invalid argument: Default column family not specified
[ERROR] Plugin 'STONEDB' init function returned error.
[ERROR] Plugin 'STONEDB' registration as a STORAGE ENGINE failed.

```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Please, Gives the more messages, which can tell the root cause.. @lylth
