### ISSUE TITLE
feature: to support ` replace into  values()` SQL synax 

### ISSUE THREAD

**Issue by isredstar** [stoneatom/stonedb#1011]
**Is your feature request related to a problem? Please describe.**

To support ` replace into  values()` SQL synax.
For example: REPLACE INTO test VALUES(1,'Old','2014-08-20 18:47:00');.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by isredstar** [comment]
ACK

**Comment by isredstar** [comment]
ADD `DUP_REPLACE`

> int ha_tianmu::write_row([[maybe_unused]] uchar *buf) {
  int ret = 1;
  DBUG_ENTER(__PRETTY_FUNCTION__);
  try {
    if (ha_thd()->lex->duplicates == DUP_UPDATE) {
      if (auto indextab = ha_tianmu_engine_->GetTableIndex(table_name_)) {
        if (size_t row; has_dup_key(indextab, table, row)) {
          dupkey_pos_ = row;
          DBUG_RETURN(HA_ERR_FOUND_DUPP_KEY);
        }
      }
    }
    ret = ha_tianmu_engine_->InsertRow(table_name_, current_txn_, table, share_);
  } catch (common::OutOfMemoryException &e) {
    DBUG_RETURN(ER_LOCK_WAIT_TIMEOUT);
  } catch (common::DatabaseException &e) {
    TIANMU_LOG(LogCtl_Level::ERROR, "An exception is caught in Engine::InsertRow: %s.", e.what());
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), e.what(), MYF(0));
  } catch (common::FormatException &e) {
    TIANMU_LOG(LogCtl_Level::ERROR, "An exception is caught in Engine::InsertRow: %s Row: %ld, field %u.", e.what(),
               e.m_row_no, e.m_field_no);
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), e.what(), MYF(0));
  } catch (common::FileException &e) {
    TIANMU_LOG(LogCtl_Level::ERROR, "An exception is caught in Engine::InsertRow: %s.", e.what());
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), e.what(), MYF(0));
  } catch (common::Exception &e) {
    TIANMU_LOG(LogCtl_Level::ERROR, "An exception is caught in Engine::InsertRow: %s.", e.what());
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), e.what(), MYF(0));
  } catch (std::exception &e) {
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), e.what(), MYF(0));
    TIANMU_LOG(LogCtl_Level::ERROR, "An exception is caught in Engine::InsertRow: %s.", e.what());
  } catch (...) {
    my_message(static_cast<int>(common::ErrorCode::UNKNOWN_ERROR), "An unknown system exception error caught.", MYF(0));
    TIANMU_LOG(LogCtl_Level::ERROR, "An unknown system exception error caught.");
  }
  DBUG_RETURN(ret);
}

**Comment by isredstar** [comment]
```
Tianmu::handler::ha_tianmu::write_row(Tianmu::handler::ha_tianmu * const this, uchar * buf) (\home\src\stonedb\storage\tianmu\handler\ha_tianmu.cpp:458)
handler::ha_write_row(handler * const this, uchar * buf) (\home\src\stonedb\sql\handler.cc:8189)
write_record(THD * thd, TABLE * table, COPY_INFO * info, COPY_INFO * update) (\home\src\stonedb\sql\sql_insert.cc:1547)
Sql_cmd_insert::mysql_insert(Sql_cmd_insert * const this, THD * thd, TABLE_LIST * table_list) (\home\src\stonedb\sql\sql_insert.cc:778)
Sql_cmd_insert::execute(Sql_cmd_insert * const this, THD * thd) (\home\src\stonedb\sql\sql_insert.cc:3151)
mysql_execute_command(THD * thd, bool first_level) (\home\src\stonedb\sql\sql_parse.cc:3620)
mysql_parse(THD * thd, Parser_state * parser_state) (\home\src\stonedb\sql\sql_parse.cc:5622)
dispatch_command(THD * thd, const COM_DATA * com_data, enum_server_command command) (\home\src\stonedb\sql\sql_parse.cc:1495)
do_command(THD * thd) (\home\src\stonedb\sql\sql_parse.cc:1034)
handle_connection(void * arg) (\home\src\stonedb\sql\conn_handler\connection_handler_per_thread.cc:313)
pfs_spawn_thread(void * arg) (\home\src\stonedb\storage\perfschema\pfs.cc:2197)
libpthread.so.0!start_thread (未知源:0)
libc.so.6!clone (未知源:0)
```

**Comment by isredstar** [comment]
**SQL syntax：**
`REPLACE [LOW_PRIORITY | DELAYED]
    [INTO] tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    [(col_name [, col_name] ...)]
    {VALUES | VALUE} (value_list) [, (value_list)] ...

REPLACE [LOW_PRIORITY | DELAYED]
    [INTO] tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    SET assignment_list

REPLACE [LOW_PRIORITY | DELAYED]
    [INTO] tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    [(col_name [, col_name] ...)]
    SELECT ...

value:
    {expr | DEFAULT}

value_list:
    value [, value] ...

assignment:
    col_name = value

assignment_list:
    assignment [, assignment] ...`

**REPLACE** works exactly like **INSERT**, except that if an old row in the table has the same value as a new row for a **PRIMARY KEY** , the old row is deleted before the new row is inserted. 

**REPLACE** either inserts, or deletes and inserts. For another StoneDB extension to standard SQL—that either inserts or updates—see _INSERT ... ON DUPLICATE KEY UPDATE Statement_

**DELAYED** inserts and replaces were deprecated, DELAYED is not supported. The server recognizes but ignores the DELAYED keyword, handles the replace as a nondelayed replace, and generates an ER_WARN_LEGACY_SYNTAX_CONVERTED warning: **REPLACE DELAYED** is no longer supported. The statement was converted to REPLACE.

**Comment by isredstar** [comment]
StoneDB uses the following algorithm for **REPLACE**:
**1. Try to insert the new row into the table**
**2. While the insertion fails because a duplicate-key error occurs for a primary key or unique index:**
-   Delete from the table the conflicting row that has the duplicate key value.
-   Try again to insert the new row into the table

**Comment by wisehead** [comment]
I noticed the code is delivered, can we close the issue?
