### ISSUE TITLE
bug: cmake .. -DENABLE_GCOV=1 faild

### ISSUE THREAD

**Issue by zsp108** [stoneatom/stonedb#1031]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

cmake .. -DENABLE_GCOV=1 
make -j32 faild in centos7
but debian 10 is ok
<img width="793" alt="lQLPJxbrHQ4aPg7NA_LNBjGwpDPg1Q4ZtB4Dgka4pID7AA_1585_1010" src="https://user-images.githubusercontent.com/31213457/204698181-2e753fe8-8a72-466e-9383-d519e827fedf.png">

### How To Reproduce

```
cmake ../ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/stonedb57/install \
          -DMYSQL_DATADIR=/stonedb57/install/data \
          -DSYSCONFDIR=/stonedb57/install \
          -DMYSQL_UNIX_ADDR=/stonedb57/install/tmp/mysql.sock \
          -DWITH_EMBEDDED_SERVER=OFF \
          -DWITH_TIANMU_STORAGE_ENGINE=1 \
          -DWITH_MYISAM_STORAGE_ENGINE=1 \
          -DWITH_INNOBASE_STORAGE_ENGINE=1 \
          -DWITH_PARTITION_STORAGE_ENGINE=1 \
          -DMYSQL_TCP_PORT=3306 \
          -DENABLED_LOCAL_INFILE=1 \
          -DEXTRA_CHARSETS=all \
          -DDEFAULT_CHARSET=utf8 \
          -DDEFAULT_COLLATION=utf8_general_ci \
          -DDOWNLOAD_BOOST=0 \
          -DWITH_BOOST=/usr/local/stonedb-boost/ \
          -DDOWNLOAD_ROCKSDB=0 \
          -DWITH_ROCKSDB=/usr/local/stonedb-gcc-rocksdb/ \
          -DWITH_MARISA=/usr/local/stonedb-marisa/ \
          -DDOWNLOAD_ROCKSDB=0 \
          -DWITH_ROCKSDB=/usr/local/stonedb-gcc-rocksdb -DENABLE_GCOV=1 && make -j`nproc`
```

### Environment

Linux zhx-test 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by lujiashun** [comment]
ACK
