### ISSUE TITLE
bug: A table of type NUMERIC, inserting a maximum value, displayed as 0

### ISSUE THREAD

**Issue by 422351990** [StoneAtom/stonedb#104]
**Describe the problem**
A table of type NUMERIC, inserting a maximum value, displayed as 0

**Expected behavior**
The expected values are 9999999999999999999999999999.9999999999、-9999999999999999999999999999.9999999999

**How To Reproduce**
Execute to create tables of type DECIMAL
```
Create Table: CREATE TABLE `TYPE009` (
  `COL` decimal(18,10) DEFAULT NULL
) ENGINE=STONEDB DEFAULT CHARSET=utf8
```

Perform the maximum value of the insert NUMERIC (38,10) type
Perform insert minimum values of type DECIMAL (38,10)
```
INSERT INTO TYPE009 VALUES(99999999.9999999999);
INSERT INTO TYPE009 VALUES(-99999999.9999999999);
SELECT * FROM TYPE009;
```

**Environment**
Ubuntu 20.04.4 LTS
Server version: 5.6.24-StoneDB

**Additional context**
none

**Comment by haitaoguan** [comment]
This Bug is the same as Bug 103。
https://github.com/stoneatom/stonedb/issues/103
@hustjieke

**Comment by hustjieke** [comment]
related to #103
