### ISSUE TITLE
bug: cmake add `-DENABLE_GCOV=1` build stonedb，mtr suite=tianmu delete timeout after 900 seconds

### ISSUE THREAD

**Issue by zsp108** [stoneatom/stonedb#1047]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

cmake add `-DENABLE_GCOV=1` build stonedb，

./mysql-test-run.pl --suite=tianmu --nowarnings --force --nocheck-testcases --retry=0 --parallel=10
delete test timeout after 900 seconds
![image](https://user-images.githubusercontent.com/31213457/204979327-c7f6dfe2-e411-42d3-81ef-cb814e66ecee.png)

only delete test is ok

### How To Reproduce

```shell
cmake ../ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/stonedb57/install \
          -DMYSQL_DATADIR=/stonedb57/install/data \
          -DSYSCONFDIR=/stonedb57/install \
          -DMYSQL_UNIX_ADDR=/stonedb57/install/tmp/mysql.sock \
          -DWITH_EMBEDDED_SERVER=OFF \
          -DWITH_TIANMU_STORAGE_ENGINE=1 \
          -DWITH_MYISAM_STORAGE_ENGINE=1 \
          -DWITH_INNOBASE_STORAGE_ENGINE=1 \
          -DWITH_PARTITION_STORAGE_ENGINE=1 \
          -DMYSQL_TCP_PORT=3306 \
          -DENABLED_LOCAL_INFILE=1 \
          -DEXTRA_CHARSETS=all \
          -DDEFAULT_CHARSET=utf8 \
          -DDEFAULT_COLLATION=utf8_general_ci \
          -DDOWNLOAD_BOOST=0 \
          -DWITH_BOOST=/usr/local/stonedb-boost/ \
          -DDOWNLOAD_ROCKSDB=0 \
          -DWITH_ROCKSDB=/usr/local/stonedb-gcc-rocksdb/ \
          -DWITH_MARISA=/usr/local/stonedb-marisa/ \
          -DDOWNLOAD_ROCKSDB=0 \
          -DWITH_ROCKSDB=/usr/local/stonedb-gcc-rocksdb -DENABLE_GCOV=1 && make -j`nproc` && make -j`nproc` install

          mkdir -p /stonedb57/install/log
          groupadd mysql && useradd -g mysql mysql
          chown -R mysql:mysql /stonedb57 && chown -R mysql:mysql ./build
          cd /stonedb57/install/mysql-test
          ./mysql-test-run.pl --suite=tianmu --nowarnings --force --nocheck-testcases --retry=0 --parallel=10


```

### Environment

build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: c5e9ef283
        Last commit time: Date:   Wed Nov 30 11:30:52 2022 +0800
        Build time: Date: Thu Dec  1 06:17:00 UTC 2022

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by konghaiya** [comment]
The problem is that the test took too long in slow I/O and triggered a test case timeout. The number of operations needs to be reduced to shorten the test time.
