### ISSUE TITLE
bug：Verify that the connection operation supports the comparison operator <

### ISSUE THREAD

**Issue by 422351990** [StoneAtom/stonedb#106]
bug：Verify that the connection operation supports the comparison operator <

**Describe the problem**
Verify that the connection operation supports the comparison operator <

**Expected behavior**
Expected value: (tom,50.11).
Actual value: Empty set (0.01 sec)

**How To Reproduce**
```
CREATE TABLE T81(bookname char(10),price float);
INSERT INTO T81 VALUES('delphi',50.11);
CREATE TABLE T82(bookname char(10),author char(10));
INSERT INTO T82 VALUES('java','tom');

SELECT AUTHOR,PRICE FROM T81 INNER JOIN T82 ON T81.BOOKNAME<T82.BOOKNAME;
```

**Environment**
Ubuntu 20.04.4 LTS
Server version: 5.6.24-StoneDB

**Additional context**
MySQL5.7 will return Expected value: (tom,50.11).

**Comment by hustjieke** [comment]
5.6 branch has been frozen.
