### ISSUE TITLE
bug: Adding a primary key constraint succeeds even if there is duplicate data

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1071]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> create table ttt(id int,name varchar(5));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into ttt values(1,'张三'),(2,'李四'),(1,'张三');
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from ttt;
+------+--------+
| id   | name   |
+------+--------+
|    1 | 张三   |
|    2 | 李四   |
|    1 | 张三   |
+------+--------+
3 rows in set (0.00 sec)

mysql> alter table ttt add constraint pk primary key(id);
Query OK, 3 rows affected (0.04 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: ttt
Create Table: CREATE TABLE `ttt` (
  `id` int(11) NOT NULL,
  `name` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> select * from ttt;
+----+--------+
| id | name   |
+----+--------+
|  1 | 张三   |
|  2 | 李四   |
|  1 | 张三   |
+----+--------+
3 rows in set (0.01 sec)
```

### Expected behavior

```sql
mysql> alter table ttt add constraint pk primary key(id);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
```

### Environment

./mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:HEAD
        Branch name: HEAD
        Last commit ID: b44a51ce8
        Last commit time: Date:   Fri Dec 2 16:11:06 2022 +0000
        Build time: Date: Mon Dec  5 06:12:44 UTC 2022

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by adofsauron** [comment]
1) Create a table to specify the primary key, which can play the role of primary key constraint;

2) When creating a table, the primary key is not specified. Instead, the alter command is used to add the table, which cannot play the role of primary key constraint.

Note: In most cases, the primary key is defined during the table design phase and is rarely re-planned after production. The alter command added the primary key to avoid the master-slave interrupt was developed last week and cannot be enabled to the constraint effect and then scheduled optimization.
