### ISSUE TITLE
bug: Create table Primary key set AUTO_INCREMENT  missing  data in a certain case.

### ISSUE THREAD

**Issue by nangong007** [stoneatom/stonedb#1072]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

when set  global  tianmu_insert_delayed =ON，innodb_autoinc_lock_mode=1 ;  and update primary key manually to a new value. Then will missing a row.

For example:
CREATE TABLE:
CREATE TABLE employees (
    emp_no INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50)
); 
INSERT INTO employees(first_name,last_name)
VALUES('John','Doe'),
      ('Mary','Jane'); 

UPDATE employees 
SET 
    first_name = 'Joe',
    emp_no = 5
WHERE
    emp_no = 2; 

INSERT INTO employees(first_name,last_name)
VALUES('Wang2','Lee'); 
INSERT INTO employees(first_name,last_name)
VALUES('Wang3','Lee'); 
INSERT INTO employees(first_name,last_name)
VALUES('Wang4','Lee'); 
INSERT INTO employees(first_name,last_name)
VALUES('Wang5','Lee'); 
INSERT INTO employees(first_name,last_name)
VALUES('Wang6','Lee'); 

Result:
 The row where first_name='Wang5'   is missing

expecting:

The row where first_name='Wang5'  should exist in table.

### Expected behavior

No row  missing 

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by isredstar** [comment]
ACK

**Comment by isredstar** [comment]
`void ha_tianmu::update_create_info([[maybe_unused]] HA_CREATE_INFO *create_info) {} `  is not implemented

**Comment by RingsC** [comment]
fix by #1315
