### ISSUE TITLE
bug: (Primary/Secondary)After a column is added.Data on the primary database and that on the secondary database are inconsistent.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1074]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

###master
```sql
create table ttt(id int primary key,name varchar(5));
insert into ttt values(1,'AAA'),(2,'BBB');
alter table ttt add column age int not null;
mysql> select * from ttt;
+----+------+-----+
| id | name | age |
+----+------+-----+
|  1 | AAA  |   0 |
|  2 | BBB  |   0 |
+----+------+-----+
2 rows in set (0.00 sec)
```

###slave
```sql
mysql> select * from ttt;
+----+------+-----+
| id | name | age |
+----+------+-----+
| NULL | AAA  | NULL |
| NULL | BBB  | NULL |
+----+------+-----+
2 rows in set (0.00 sec)
```

### Expected behavior

###slave
```sql
mysql> select * from ttt;
+----+------+-----+
| id | name | age |
+----+------+-----+
|  1 | AAA  |   0 |
|  2 | BBB  |   0 |
+----+------+-----+
2 rows in set (0.00 sec)
```

### Environment

./mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:HEAD
        Branch name: HEAD
        Last commit ID: b44a51ce8
        Last commit time: Date:   Fri Dec 2 16:11:06 2022 +0000
        Build time: Date: Mon Dec  5 06:12:44 UTC 2022

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by DandreChen** [comment]
ACK

**Comment by konghaiya** [comment]
The reason for this problem should be that not null does not take effect when adding columns,
Innodb assigns a value of 0 by default, but tianmu directly assigns a value of null.
Therefore, we need to troubleshoot the problem that not null does not take effect when adding new columns.

**Comment by DandreChen** [comment]
test case without primary key：
```
mysql> create table ttt(id int,name varchar(5));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into ttt values(1,'AAA'),(2,'BBB');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> alter table ttt add column age int not null;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> select * from ttt;
+------+------+-----+
| id   | name | age |
+------+------+-----+
|    1 | AAA  | NULL |
|    2 | BBB  | NULL |
+------+------+-----+
2 rows in set (0.00 sec)

```

**Comment by DandreChen** [comment]
the inplace method of tianmu don‘t support primary key
need support primary key

**Comment by DandreChen** [comment]
the similar to #1188
