### ISSUE TITLE
docs: Developer Guide Document Optimization

### ISSUE THREAD

**Issue by TomeC** [stoneatom/stonedb#1077]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Description

1. The lib file compiled by google test is different in 32-bit operating system and 64 bit operating system.
2. Initialize the connection, add the sql that allows the root to log in remotely.

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by adofsauron** [comment]
Thanks for asking, but I have a few questions about ssh clone.
How do you ensure that each machine with clone code has added its own ssh key to github's repository?
Especially when there is a CI/CD that automatically pulls up a container for a linux distribution?

```
googletest Clones may be rejected and ssh calls instead.
```

**Comment by TomeC** [comment]
> Thanks for asking, but I have a few questions about ssh clone. How do you ensure that each machine with clone code has added its own ssh key to github's repository? Especially when there is a CI/CD that automatically pulls up a container for a linux distribution?
> 
> ```
> googletest Clones may be rejected and ssh calls instead.
> ```

You are right. I have modified the content.
