### ISSUE TITLE
bug: When tianmu_insert_delayed is ON, the `tinyint(4) unsigned`  is invalid

### ISSUE THREAD

**Issue by isredstar** [stoneatom/stonedb#1082]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

**tianmu_insert_delayed = ON**
```
mysql> create table test4(id tinyint(4) unsigned not null) engine=tianmu;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test4 values(129);
Query OK, 1 row affected (7.81 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 127 |
+-----+
1 rows in set (0.01 sec)
```
**tianmu_insert_delayed = OFF**
```
mysql> insert into test4 values(129);
Query OK, 1 row affected (21.92 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 127 |
| 129 |
+-----+
2 rows in set (0.01 sec)

```

### Expected behavior

**tianmu_insert_delayed = ON**
```
mysql> create table test4(id tinyint(4) unsigned not null) engine=tianmu;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test4 values(129);
Query OK, 1 row affected (7.81 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 129 |
+-----+
1 rows in set (0.01 sec)
```
**tianmu_insert_delayed = OFF**
```
mysql> insert into test4 values(129);
Query OK, 1 row affected (21.92 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 129 |
| 129 |
+-----+
2 rows in set (0.01 sec)

```

### How To Reproduce

**tianmu_insert_delayed = ON**
```
mysql> create table test4(id tinyint(4) unsigned not null) engine=tianmu;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test4 values(129);
Query OK, 1 row affected (7.81 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 127 |
+-----+
1 rows in set (0.01 sec)
```
**tianmu_insert_delayed = OFF**
```
mysql> insert into test4 values(129);
Query OK, 1 row affected (21.92 sec)

mysql> select * from test4;
+-----+
| id  |
+-----+
| 127 |
| 129 |
+-----+
2 rows in set (0.01 sec)

```

### Environment

./sql/mysqld  Ver 5.7.36-StoneDB-debug for Linux on x86_64 (build-)
build information as follow: 
	Repository address: https://github.com/isredstar/stonedb.git:stonedb-5.7-dev
	Branch name: stonedb-5.7-dev
	Last commit ID: 787e0bc1
	Last commit time: Author: HongXing <63028664+isredstar@users.noreply.github.com>
	Build time: Date: Wed 07 Dec 2022 03:27:15 AM UTC

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by isredstar** [comment]
ACK

**Comment by hustjieke** [comment]
related to issue https://github.com/stoneatom/stonedb/issues/1218 and fixed in pr https://github.com/stoneatom/stonedb/pull/1220
