### ISSUE TITLE
feature: sql_mode set  MANDATORY_TIANMU  do not work

### ISSUE THREAD

**Issue by nangong007** [stoneatom/stonedb#1131]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

SQL_MODE:
SQL_MODE= 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,MANDATORY_TIANMU'

CREATE TABLE:

CREATE TABLE `customers3` (
  `customerNumber` int(11) NOT NULL,
  `customerName` varchar(50) NOT NULL,
  `contactLastName` varchar(50) NOT NULL,
  `contactFirstName` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `addressLine1` varchar(50) NOT NULL,
  `addressLine2` varchar(50) DEFAULT NULL,
  `city` varchar(50) NOT NULL,
  `state` varchar(50) DEFAULT NULL,
  `postalCode` varchar(15) DEFAULT NULL,
  `country` varchar(50) NOT NULL,
  `salesRepEmployeeNumber` int(11) DEFAULT NULL,
  `creditLimit` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`customerNumber`),
  KEY `salesRepEmployeeNumber` (`salesRepEmployeeNumber`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

SHOW CREATE TABLE  customers3:

![image](https://user-images.githubusercontent.com/61264225/207797818-b06bca9a-711a-43a7-abdf-8eac765bf159.png)

### Expected behavior

ENGINE should be TIANMU

### Environment

/opt/stonedb57/install/bin/mysqld --version

 Last commit ID: 5eff82163
 Last commit time: Date:   Wed Dec 14 12:35:22 2022 +0800

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by konghaiya** [comment]
When testing this parameter, you need to set the global level, and it only takes effect on the slave library. In a stand-alone scenario, this parameter is invalid
