### ISSUE TITLE
feature: change stonedb.cnf to my.cnf

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#117]
**Is your feature request related to a problem? Please describe.**

```
$ ls /stonedb56/install/
bin     cache    data  include         install.sh  log  my.cnf      mysql_server  README        scripts  sql-bench    support-files
binlog  COPYING  docs  INSTALL-BINARY  lib         man  my-new.cnf  mysql-test    reinstall.sh  share    stonedb.cnf  tmp
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Perhaps, some third-party mysql tool monitor mysql instance via reading my.cnf, therefore, the tools find out configuration file with name `my.cnf`, `stonedb.cnf` may lead to an error.
