### ISSUE TITLE
bug: If you move the basedir(stonedb57)，the script reinstall.sh will fail.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1181]
By default, the basedir is /opt/stonedb57/install. If you move the basedir,then you execute the script reinstall.sh will fail.
We know the script reinstall.sh calls another script mysql_server, and the basedir of the script mysql_server is still /opt/stonedb57/install. 
```sql
# cd /opt
# mv stonedb57 /
# cd /stonedb57/install/
# ./reinstall.sh
```

**Comment by e1ijah1** [comment]
It looks like we need to rebuild install scripts, but the `stonedb_build.sh` script does not currently support rebuilding these install scripts.

**Comment by hustjieke** [comment]
> It looks like we need to rebuild install scripts, but the `stonedb_build.sh` script does not currently support rebuilding these install scripts.

Make sense, can you submit a pr to fix this problem?

**Comment by e1ijah1** [comment]
> > It looks like we need to rebuild install scripts, but the `stonedb_build.sh` script does not currently support rebuilding these install scripts.
> 
> Make sense, can you submit a pr to fix this problem?

Yes, I'd like to try it. Please assign me this issue.

**Comment by hustjieke** [comment]
> > > It looks like we need to rebuild install scripts, but the `stonedb_build.sh` script does not currently support rebuilding these install scripts.
> > 
> > 
> > Make sense, can you submit a pr to fix this problem?
> 
> Yes, I'd like to try it. Please assign me this issue.

Great, looking forward to your pr!

**Comment by e1ijah1** [comment]
I found some problems when I checked it again. If we use `stonedb_build.sh` to recompile the install scripts, we may have to download the whole repository and install the dependencies. Would there be a simpler way to accomplish this?

**Comment by haitaoguan** [comment]
Third party dependency libraries(marisa、rocksdb、boost) are not reinstalled

**Comment by adofsauron** [comment]
You can refer to the compilation script I modified:

https://gitcode.net/adofsauron/stonedb-dev-20230103/-/blob/stonedb-5.7-dev/scripts/stonedb_build.sh

**Comment by e1ijah1** [comment]
> https://gitcode.net/adofsauron/stonedb-dev-20230103/-/blob/stonedb-5.7-dev/scripts/stonedb_build.sh

It seems that some scripts, such as "stonedb57/install/bin/mysqld_multi" and "stonedb57/install/support-files/mysql-log-rotate", still link to the target path "stonedb57/install" specified before build, so reinstall.sh doesn't work after moving the base directory.

**Comment by adofsauron** [comment]
> > https://gitcode.net/adofsauron/stonedb-dev-20230103/-/blob/stonedb-5.7-dev/scripts/stonedb_build.sh
> 
> It seems that some scripts, such as "stonedb57/install/bin/mysqld_multi" and "stonedb57/install/support-files/mysql-log-rotate", still link to the target path "stonedb57/install" specified before build, so reinstall.sh doesn't work after moving the base directory.

the compile script only compiles and does not solve other problems

**Comment by adofsauron** [comment]
> 

work hard

**Comment by e1ijah1** [comment]
> > 
> 
> work hard

The problem won't be solved by just saying "work hard".

**Comment by hustjieke** [comment]
Have you compiled it in your env? If not,  compilation and installation are inevitable, you can follow the compile docs:
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu20.04-for-57/

**Comment by RingsC** [comment]
@e1ijah1 , Re-creates the base dir when these dirs do not exits. Firstly, to check out the existence of these dirs, then, not exists, creates it, or do nothing.  So what do u think? Any idea?

```bash
if [ ! -d "/myfolder" ]; then
  mkdir /myfolder
fi
```

**Comment by haitaoguan** [comment]
If your installation path is non default by /stonedb57/install.You need to modify the file of mysql_server,the following:
  basedir=/xxx/stonedb57/install
  bindir=/xxx/stonedb57/install/bin
  datadir=/xxx/stonedb57/install/data
  sbindir=/xxx/stonedb57/install/bin
  libexecdir=/xxx/stonedb57/install/bin
