### ISSUE TITLE
feature: Master-slave synchronization, bit type supported by conditional push

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#1230]
**Is your feature request related to a problem? Please describe.**

Master-slave synchronization, bit type supported by conditional push
**Describe the solution you'd like**

Add bit type support in conditional push logic
**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
@konghaiya what mainly purpose for this issue？ Would you like give more info on this issue, and pls fills up the issue template.
