### ISSUE TITLE
feature: add makefile and dockerfile for build

### ISSUE THREAD

**Issue by lxd5866** [stoneatom/stonedb#125]
how about add makefile with dockerfile to build project

**Comment by RingsC** [comment]
yes, your PR is welcome.

**Comment by hustjieke** [comment]
Good question, we have a build file: 
https://github.com/stoneatom/stonedb/blob/stonedb-5.6/scripts/stonedb_build.sh
and the docker building env is here: 
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-docker/
Maybe the links above should be easier for users to see, a good fisrt pr is welcome for you. @lxd5866
