### ISSUE TITLE
feature: show stonedb tag version

### ISSUE THREAD

**Issue by lujiashun** [stoneatom/stonedb#1251]
**Is your feature request related to a problem? Please describe.**

release version format：5.7.36-StoneDB-v1.0.3  
debug version format：5.7.36-StoneDB-v1.0.3.abcdefaaa  (abcdefaaa  means the first 9 digits of commit id string)
related：
1. mysql welcome page
2. select version()
3. mysqld --version
4. related logs

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Do we really need this tag name? we can identify stonedb by commit id. and this has already in stonedb. And, the tage name can be CHANGED that will make tag to be a temporary thing, and CAN NOT to identify it.
