### ISSUE TITLE
docs: typos in README

### ISSUE THREAD

**Issue by amber-moe** [stoneatom/stonedb#1254]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Description

![image](https://user-images.githubusercontent.com/42762957/215420001-a63a30f7-5c9c-4dbc-b81f-33e9f1968dce.png)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by hustjieke** [comment]
Thanks for pointed out the typos, would you like to make a pr for this problem? @Amber1990Zhang

**Comment by Nliver** [comment]
Thanks for reminding us, I didn't expect you as a foreign Vtuber to read our Readme so carefully, I am very moved, we will update this punctuation mark soon, you did a great job! Look forward to your continued attention!
