### ISSUE TITLE
bug: on centos build src,  occor mysqld.cc:8134:31: error: 'STONEDB_TAG_NAME' was not declared in this scope

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1262]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

https://github.com/stoneatom/stonedb/actions/runs/4054123361/jobs/6975578986

```c++

/__w/stonedb/stonedb/sql/mysqld.cc: In function 'void set_server_version()':
/__w/stonedb/stonedb/sql/mysqld.cc:8134:31: error: 'STONEDB_TAG_NAME' was not declared in this scope; did you mean 'STONEDB_BRANCH_NAME'?
 8134 |       static_cast<int>(sizeof(STONEDB_TAG_NAME)))
      |                               ^~~~~~~~~~~~~~~~
      |                               STONEDB_BRANCH_NAME

```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by lujiashun** [comment]
ACK
