### ISSUE TITLE
bug:  Type 'help' or '\h' for help doesn't work

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1323]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> help select

Nothing found
Please try to run 'help contents' for a list of all accessible topics

mysql> \h select

Nothing found
Please try to run 'help contents' for a list of all accessible topics

```

### Expected behavior

```shell
mysql> help select
Name: 'SELECT'
Description:
Syntax:
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
    [HIGH_PRIORITY]
    [STRAIGHT_JOIN]
    [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
    [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr] ...
    [into_option]
    [FROM table_references
      [PARTITION partition_list]]

```

### Environment

```shell
root@ub01:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.2 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 0f4250589
        Last commit time: Date:   Tue Feb 21 06:09:37 2023 +0000
        Build time: Date: Wed Feb 22 17:50:51 CST 2023
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by RingsC** [comment]
The fill the script/fill_help_tables.sql. via 
https://github.com/mysql/mysql-server/blob/8.0/scripts/fill_help_tables.sql

or 
https://github.com/GreatSQL/GreatSQL/blob/greatsql-5.7.36/scripts/fill_help_tables.sql

**Comment by qiuyuyin** [comment]
Can I give it a try?

**Comment by hustjieke** [comment]
> Can I give it a try?

Welcome!  It'll be great to submit a PR to solve the problem.
You can comment here if meet any problem.

**Comment by qiuyuyin** [comment]
just add this fill_help_tables.sql file to adapt to StoneDB's current SQL statements?

**Comment by RingsC** [comment]
> 
@qiuyuyin 
After this file filled,  a header, 'scripts/sql_commands_help_data.h', file will be created in compiling stage by cmake. 

the content of that file is as following: all the help messages are defined in fill_help_tables, which selects from that sql file.
```
 1 /*
  2   Do not edit this file, it is automatically generated from:
  3   </home/lihao/workshop/stonedb-ver-1.0/scripts/fill_help_tables.sql>
  4 */
  5 const char* fill_help_tables[]={
  6 NULL
  7 };
```

~

**Comment by El-even-11** [comment]
Hey @qiuyuyin , are you still working on/interested in this issue?

**Comment by qiuyuyin** [comment]
> Hey @qiuyuyin , are you still working on/interested in this issue?

Are you interested in this? you can do it. I am a little busy now.

**Comment by El-even-11** [comment]
> Are you interested in this? you can do it. I am a little busy now.

Yes! Thanks a lot!
