### ISSUE TITLE
docs: typo in compiling guidance (zh stonedb5.7 ubuntu20.04)

### ISSUE THREAD

**Issue by El-even-11** [stoneatom/stonedb#1339]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Description

[Ubuntu 20.04 下编译 StoneDB for MySQL5.7](https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu20.04-for-57/#3-%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85)

![image](https://user-images.githubusercontent.com/73071130/221803153-5b0992b7-9395-4244-9cb4-6ba1b880b0e8.png)

stonedb56 -> stonedb57

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Nliver** [comment]
This issue has been resolved by #1340 and I will close it.
