### ISSUE TITLE
bug: Relevant resources are not released after a thread is killed.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1352]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
###session1
mysql> use db;
Database changed
mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: ttt
Create Table: CREATE TABLE `ttt` (
  `id` bigint(10) NOT NULL,
  `c_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8
1 row in set (0.01 sec)

mysql> select count(*) from ttt;
+----------+
| count(*) |
+----------+
|  3841782 |
+----------+
1 row in set (0.01 sec)

mysql> explain select c_date
    ->   from ttt
    ->  where c_date >= date_sub(now(), interval 30 day)
    ->    AND c_date < now();

###session 2
mysql> show processlist;
......
mysql> kill 20;
Query OK, 0 rows affected (0.00 sec)

mysql> show processlist;
······
| 20 | root | localhost | charge_order | Killed  |  496 | explaining | explain select c_date
  from ttt
 where c_date >= date_sub(now(), interval 30 day)
   AND c_date <  |
......
```

### Environment

build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 3e66e1432
        Last commit time: Date:   Tue Feb 28 16:54:01 2023 +0800
        Build time: Date: Thu Mar  2 17:09:04 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by adofsauron** [comment]
### disable explain on tianmu table

Now that the execution plan of explain output has been converted into a query tree in stonedb, it is better to mask explain without the function directly, which will not cause cpu inflation, and wait until the explain function is perfected in the future

**Comment by adofsauron** [comment]
```sql

explain select c_date
       from ttt
      where c_date >= date_sub(now(), interval 30 day)
      AND c_date < now();

```

**Comment by adofsauron** [comment]
1. Check whether the left and right addresses are the same

2. Add comparisons for fetch data with ITEM_CACHE

3. dawn_cast function encapsulated by mysql is used for downcasting to avoid runtime risks

**Comment by adofsauron** [comment]
![65cf9db58a2c4f5372d223fb0bea4e08](https://user-images.githubusercontent.com/3915817/222678511-1585cf50-1e8d-4f81-992d-c8e6f214de9f.png)

**Comment by RingsC** [comment]
Nice job.
