### ISSUE TITLE
feature: Delta layer, add the command to view the playback progress

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#1359]
**Is your feature request related to a problem? Please describe.**

Add the command to view the progress of playback from Rocksdb to Tianmu Base layer to determine whether the data is synchronized
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
Do you have idea how to do it?
Add a series of `StoneDB ctl` sql commands or embedded the re-play infos into the `show slave status`?

**Comment by konghaiya** [comment]
The purpose of adding this command is not to view the slave status, but to view the synchronization progress from Rocksdb temporary line storage to column storage
To achieve this goal, we need to add a new view instruction, such as: (show Tianmu Delta table_name status;)
(table_name) can be empty. If it is empty, the overall synchronization of the Delta layer will be returned.

**Comment by konghaiya** [comment]
At present, the information of the delta layer is printed out through logs, and the code logic is shown in the following figure:
<img width="840" alt="image" src="https://github.com/stoneatom/stonedb/assets/106147765/53f3e33c-2bdc-473f-9e52-deff77aaae93">

We expect to output this information by adding instructions to MySQL
