### ISSUE TITLE
bug:  the range of bigint value problem

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1361]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> CREATE TABLE int8_tbl(q1 int8, q2 int8);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO int8_tbl VALUES ('-9223372036854775805','-9223372036854775807');
ERROR 1264 (22003): Out of range[-9223372036854775807, 9223372036854775807] for column 'q2' value: -9223372036854775807

```

### Expected behavior

`The value range of bigint should be determined`

### How To Reproduce

```sql
CREATE TABLE int8_tbl(q1 int8, q2 int8);
INSERT INTO int8_tbl VALUES ('-9223372036854775805','-9223372036854775807');
```

### Environment

```shell
root@ub01:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.2 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: d66a3ca70
        Last commit time: Date:   Wed Mar 8 10:28:54 2023 +0800
        Build time: Date: Wed Mar  8 11:35:35 CST 2023
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by hustjieke** [comment]
ACK.

**Comment by El-even-11** [comment]
Let me have a try!

**Comment by hustjieke** [comment]
> Let me have a try!

Sure!
In tianmu, `bigint` supports range from `[-9223372036854775806, 9223372036854775807]`, so the error msg `ERROR 1264 (22003): Out of range[-9223372036854775807, 9223372036854775807]` should be fixed.

Correct msg: `ERROR 1264 (22003): Out of range[-9223372036854775806, 9223372036854775807]`

For more infos, see docs:
https://stonedb.io/zh/docs/SQL-reference/data-types/

**Comment by hustjieke** [comment]
The error msg takes from `PushWarningIfOutOfRange()` in `tianmu/common/common_definitions.cpp`.
The code segment, you can debug from here:
```
    case MYSQL_TYPE_LONGLONG: {
      if (unsigned_flag && (static_cast<uint64_t>(v) > TIANMU_BIGINT_MAX)) {
        PushWarning(thd, Sql_condition::SL_WARNING, ER_WARN_DATA_OUT_OF_RANGE,
                    getErrMsg(col_name, 0, TIANMU_BIGINT_MAX, unsigned_flag, v).c_str());
        throw std::exception();
      } else if (v > TIANMU_BIGINT_MAX || v <= TIANMU_BIGINT_MIN) {
        PushWarning(thd, Sql_condition::SL_WARNING, ER_WARN_DATA_OUT_OF_RANGE,
                    getErrMsg(col_name, TIANMU_BIGINT_MIN, TIANMU_BIGINT_MAX, unsigned_flag, v).c_str());
        throw std::exception();
      }
    } break;
```

**Comment by El-even-11** [comment]
Roughly three options:

1. set TIANMU_BIGINT_MIN as NULL_VALUE_64 + 1 (consistent with TIANMU_INT_MIN, NULL_VALUE + 1). May lead to other bugs.
2. for `getErrMsg()`, pass TIANMU_BIGINT_MIN + 1. A little untidy.
3. in `getErrMsg()`, change `[` to `(`. Inconsistent with other types.

**Comment by El-even-11** [comment]
I prefer the first option. If it may lead to any potential bug, then choose the second one.

**Comment by hustjieke** [comment]
> 1. NULL_VALUE_64 + 1

I alse prefer to  option 1: `TIANMU_INT_MIN  = NULL_VALUE_64 + 1 `, 
`-9223372036854775807 ` in tianmu is used to represented `NULL_VALUE_64`, so it should not be insert into tianmu.
If option 1 leads to other bugs, then try option 2.
