### ISSUE TITLE
bug: arm platform insert into failed: 6: assert failed on dpn 

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

mtr testcase :  stonedb/mysql-test/suite/tianmu/t/select.test
```shell
CURRENT_TEST: tianmu.select
mysqltest: At line 1403: query 'insert into t3 select * from t3_1' failed: 6: assert failed on dpn->CAS(expected, newv) at tianmu_attr.cpp:810, msg: [bad loading flag562922459724624. ./aa/t3_1.tianmu/columns/4 index:0]
```

### Environment

```shell
[root@localhost bin]# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on aarch64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: fb58421b3
        Last commit time: Date:   Wed Mar 15 19:32:42 2023 +0800
        Build time: Date: 2023年 03月 16日 星期四 17:59:28 CST
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by wisehead** [comment]
it's due to disk full, enlarge the disk, and the test case will pass.
