### ISSUE TITLE
backport: porting docs from v1.0.1ga

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1407]
**Is your feature request related to a problem? Please describe.**

We only need to port docs from tag v1.0.1ga.
```
$ git tag -l
5.7-v1.0.0-GA
5.7-v1.0.0-beta
5.7-v1.0.1-GA
5.7-v1.0.1-beta
5.7-v1.0.2-GA
5.7-v1.0.2-pre-release
5.7-v1.0.3-beta
stonedb-5.6-v1.0.0

$ git checkout -b feat_v1.0.1ga 5.7-v1.0.1-GA 
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
Further more: we need to make a check if this porting has impact on the official website.

**Comment by hustjieke** [comment]
ping @Nliver

**Comment by Nliver** [comment]
This work has been completed by me, I will close this issue.
