### ISSUE TITLE
feature: Memory leak check with Valgrind

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#142]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by konghaiya** [comment]
> Related problems

-  #137 
-  #110
-  #109
-  #108
-  #81
-  #80
-  #67
-  #66
-  #60

---

**Comment by hustjieke** [comment]
Nice job!
