### ISSUE TITLE
backport: fix the current version does not enable multithreaded aggregation optimization 

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1424]
**Is your feature request related to a problem? Please describe.**

commit id: 0a176af5ce9820e56fa787a8f08f6427b459b224

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
This function has modified in [b735150](https://github.com/stoneatom/stonedb/commit/b7351509304c144b626436c66e44afbf508461dc).
![Screen Shot 2023-03-28 at 20 09 17](https://user-images.githubusercontent.com/19671032/228234497-f2191659-32ef-4a4e-afaf-5e6e70c8c4ce.png)
The code of the stonedb 8.0 is consistent with 5.7 now.
