### ISSUE TITLE
backport: set clang-format

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1436]
**Is your feature request related to a problem? Please describe.**

commit id: 9fcf0dc48ef13a08e55afc9fc6bc84cb4eca652d

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
set clang-format in [#5a5d6ff](https://github.com/stoneatom/stonedb/commit/5a5d6fff841c7333dbcf09f2df37c154d4723867)
