### ISSUE TITLE
backport: fix bug:'on duplicate key update' scenario, incorrect result occurs

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1441]
**Is your feature request related to a problem? Please describe.**

previous working issue: #502
commit id: c95aa8584c673c39a5f4951651238584bdf57893

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
When tianmu_delay_insert open, duplicate key update may failed because of merge discord.
<img width="979" alt="Screen Shot 2023-04-17 at 14 50 23" src="https://user-images.githubusercontent.com/19671032/232406673-64e01dfa-bfab-4c78-9ab0-e568cd912e19.png">

**Comment by hustjieke** [comment]
> 1 fisrtly, in debug mode，there is a assertion failure， just fix it； 2 secondly, the release version will not cause this assertion failure，and will give the result，but the result is incorrect； 3 if execute the sql one by one for at least 1 seconds interval，we can see the result is correct； 4 the root reason is because of the variable ‘**tianmu_insert_delayed**’，its default value is ON， if inset one row，the data is not stored in tiamu at that time（stored later），stored in the rocksdb or memory； if setted off，the row will be dirrectly inserted into tianmu，so query result will be correct；

In StoneDB 8.0, debug mode will not crash, so we just backport the test case.
