### ISSUE TITLE
backport: Fixed when Boolean types appear in or predicates

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1442]
**Is your feature request related to a problem? Please describe.**

previous working issue #747
commit id: 58bae93d459bfc097d98cac5030d98d22c9b9e53

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
Result in InnoDB:
![Screen Shot 2023-04-13 at 16 53 35](https://user-images.githubusercontent.com/19671032/231708641-85246800-a8f8-4b49-a02f-1963edb729da.png)
Result in tianmu:
![Screen Shot 2023-04-13 at 16 56 39](https://user-images.githubusercontent.com/19671032/231708859-c2bc8f8f-4bcb-47dd-9d0b-cbda573709f2.png)
Result is correct in stonedb8.0.

**Comment by hustjieke** [comment]
In 8.0, function name has been changed to `bool remove_eq_conds(THD *thd, Item *cond, Item **retcond,`, you can compare the changes in this commit.

**Comment by hustjieke** [comment]
This is caused by #1437, if backport #1437, should be carefully.
Now the results is correct.
