### ISSUE TITLE
backport: fix assert failed on i < m_idx.size()

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1444]
**Is your feature request related to a problem? Please describe.**

previous working issue #754

- [x] commit id: 10237d73e810a0c4442337fadc7942a17e72f3bc
- [x] commit id: 86a7685dc64f8ae3ba92aed6118471cfdecb911d

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidshiz** [comment]
Temporarily unable to reproduce
