### ISSUE TITLE
bug: order by speed bug

### ISSUE THREAD

**Issue by wxfmsf** [stoneatom/stonedb#1457]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

The same table, 100 million records test，5.7.1.0.3 version order by query is slower than 5.7.1.0.2 version order by query

### Expected behavior

5.7.1.0.3 version order by query speed>=5.7.1.0.2 version order by query speed

### How To Reproduce

5.7.1.0.2

records:100000000
select * from lineitem order by l_partkey limit 1                    0.2 sec

5.7.1.0.3

records:100000000
select * from lineitem order by l_partkey limit 1                    14 sec

### Environment

centos 7.9
stonedb5.7.1.0.2   5.7.1.0.3

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by davidshiz** [comment]
set global tianmu_orderby_speedup = 0

**Comment by davidshiz** [comment]
thank you
you can` set global tianmu_orderby_speedup = 0` , it will be as fast as before

**Comment by wxfmsf** [comment]
thank you!
i test after set global tianmu_orderby_speedup = 0; yes,it is as fast before. so i closed this.
