### ISSUE TITLE
Add parameters of tianmu_mandatory  and tianmu_no_key_error

### ISSUE THREAD

**Issue by nangong007** [stoneatom/stonedb#1462]
# 1、  **tianmu_mandatory**
Specifies whether to enable mandatory Tianmu engine in table. if yes ,set **tianmu_mandatory** to **ON**, otherwise  set the variable to OFF.

<html>
<body>
<div class="lake-content" typography="classic">

Dynamic | Yes
-- | --
Scope | Global, Session
Data Type | Boolean
Value Range | ON or OFF
Default Value |  OFF
Recommended Value | OFF

</div>
</body>
</html>

### Syntax:
1、At global level:
mysql>set global tianmu_mandatory='ON';

2、 At session level:
mysql>set session tianmu_mandatory='ON';

3、 Configuration file my.cnf:
[mysqld] 
tianmu_mandatory   =  'ON'

### Priority:
tianmu_mandatory > SQL_MODE='mandatory_tianmu' > default_storage_engine

# 2、  **tianmu_no_key_error**
Specifies whether to to directly skip DDL statements that are not supported by the SQL layer, instead of reporting errors. if yes ,set **tianmu_no_key_error** to **ON**, otherwise  set the variable to OFF.

<html>
<body>
<div class="lake-content" typography="classic">

Dynamic | Yes
-- | --
Scope | Global, Session
Data Type | Boolean
Value Range | ON or OFF
Default Value |  OFF
Recommended Value | OFF

</div>
</body>
</html>

### Syntax:
1、 At global level:
mysql>set global tianmu_no_key_error='ON';

2、  At session level:
mysql>set session tianmu_no_key_error='ON';

3、  Configuration file my.cnf:
[mysqld] 
tianmu_no_key_error=  'ON'

### Priority:
tianmu_no_key_error> SQL_MODE='no_key_error'

**Comment by konghaiya** [comment]
In version 1.0.4, we will discard "MANDATORY_TIANMU" and "NO_KEY_ERROR" in (sql_mode)
