### ISSUE TITLE
bug: build stonedb fail on centos7.9 , report : error: ‘kPathNotFound’ is not a member of ‘rocksdb::Status’

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#149]
### Describe the problem

`
/root/work/stonedb/storage/stonedb/index/kv_store.cpp: In member function ‘void stonedb::index::KVStore::Init()’:
/root/work/stonedb/storage/stonedb/index/kv_store.cpp:49:94: error: ‘kPathNotFound’ is not a member of ‘rocksdb::Status’
       ((status.subcode() == rocksdb::Status::kNone) || (status.subcode() == rocksdb::Status::kPathNotFound))) {
                                                                                              ^~~~~~~~~~~~~
make[2]: *** [storage/stonedb/CMakeFiles/stonedb.dir/index/kv_store.cpp.o] Error 1
make[1]: *** [storage/stonedb/CMakeFiles/stonedb.dir/all] Error 2
make: *** [all] Error 2

`

### Environment

`CentOS Linux release 7.9.2009 (Core)`

`rocksdb-4.13`

`[root@localhost scripts]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

`

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by RingsC** [comment]
which version of rocksdb do you used? Now, The rocksdb version is 6.12.6

**Comment by adofsauron** [comment]
> 

sorry, my rocksdb version is rocksdb-4.13, upgrade rocksdb version for fix this problem.
