### ISSUE TITLE
feature: Adjust boost path in StoneDB CMakeList.txt

### ISSUE THREAD

**Issue by hustjieke** [StoneAtom/stonedb#15]
**Is your feature request related to a problem? Please describe.**

In scripts/stonedb_build.sh, the boost path:
```
-DWITH_BOOST=/usr/local/lib/boost/include
```
In StoneDB CMakeList.txt:
```
SET(BOOST_ROOT /usr/local/lib/boost)
```

**Describe the solution you'd like**

Keep the boost path consistent.

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
In PR: #325,   we adjust the `-DWITH_BOOST`  to root directory of boost, in which the boost installed.

Close this, reopen if you have another idea.

**Comment by RingsC** [comment]
In PR: #325,   we adjust the `-DWITH_BOOST`  to root directory of boost, in which the boost installed.
