### ISSUE TITLE
bug: The myloader cann't work if the autocommit is closed. 

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1510]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> create table ttt(id int primary key,name varchar(10));
Query OK, 0 rows affected (0.00 sec)

mysql> set session autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into ttt values(1,'AAA');
Query OK, 1 row affected (0.00 sec)

mysql> select * from ttt;
Empty set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from ttt;
Empty set (0.00 sec)

```

### Expected behavior

mysql> select * from ttt;
+------+------+
| id   | name |
+------+------+
|    1 | AAA  |
+------+------+
1 row in set (0.06 sec)

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 4bd09ac
        Last commit time: Date:   Fri Mar 31 09:43:11 2023 +0800
        Build time: Date: Fri Mar 31 14:02:13 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by konghaiya** [comment]
Currently, TIANMU does not support manual transactions and only supports automatic commit. However, it does determine whether to commit the transaction based on the automatic commit parameters of MySQL. If automatic commit is turned off, automatic commit will not be performed on the transaction
