### ISSUE TITLE
bug: avg(), sum() return empty but not NULL in 8.0

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1536]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

select with empty table, sum & avg return empty, not `NULL`, for max() & min(), the result is correct.
```
mysql> create table txxx(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> seect avg(a) from txxx;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'seect avg(a) from txxx' at line 1
mysql> select avg(a) from txxx;
+--------+
| avg(a) |
+--------+
|        |
+--------+
1 row in set (0.01 sec)
```

### Expected behavior

It should return `NULL`.
```
mysql> select avg(a) from txi;
+--------+
| avg(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.01 sec)
```

### Environment

stonedb-8.0-dev branch.

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by hustjieke** [comment]
@Double0101 You can try to fix it!

**Comment by Double0101** [comment]
* `sql/item.cc`
![Screen Shot 2023-04-18 at 17 31 29](https://user-images.githubusercontent.com/19671032/232735677-6a1c5115-53fe-4236-a62b-e4993e00e616.png)
Item::send function get m_data_type value to format output in MySQL 8.0.
* `storage/tianmu/core/engine_result.cpp` in scan_fields function. It use isum_int_rcbase or isum_sum_rcbase replace one of fields without set_data_type(). So in Item::send, it will get default value of m_data_type.
![Screen Shot 2023-04-18 at 17 29 16](https://user-images.githubusercontent.com/19671032/232755014-fd3bc530-1887-491a-9171-e697b5fd2bd2.png)

**Comment by Double0101** [comment]
In mysql8.0, the function use m_nullable cover the null_value, and we should set m_nullabel as well.
```c++
/* error_str() function in item.h */
 String *error_str() {
    null_value = m_nullable;
    return null_value ? nullptr : make_empty_result();
  }
/* SendRecord() function in engine_results.cpp */
Engine::Convert(is_null, isum_sum_rcbase->dec_value(), rcdt);
isum_sum_rcbase->null_value = is_null;
```
