### ISSUE TITLE
bug: A large table is executed by ddl,the tianmu.log will print a large number of error.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1545]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: ttt
Create Table: CREATE TABLE `ttt` (
  `id` int NOT NULL,
  `name` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> select count(*) from ttt;
+----------+
| count(*) |
+----------+
|  5000000 |
+----------+
1 row in set (0.00 sec)

###tianmu.log
......
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152895
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152896
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152897
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152898
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152899
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152900
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152901
[ERROR] [combined_iterator.cpp:55] MSG: base pos: 152902
......
```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 758bce8a5
        Last commit time: Date:   Mon Apr 10 19:46:20 2023 +0800
        Build time: Date: Tue 11 Apr 2023 03:30:57 AM UTC

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by konghaiya** [comment]
This is an invalid information print that needs to be deleted
