### ISSUE TITLE
bug: inconsistent result on TIMESTAMPADD function 

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1557]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

In stonedb-5.7:

```
mysql> create table tt (date_test DATE, time_test TIME, datetime_test DATETIME, timestamp_test TIMESTAMP, year_test YEAR) engine=innodb;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into tt values ('2017-12-07', '02:03:04', '2017-12-08 05:06:07', '2018-11-08 09:10:11', '2020');
Query OK, 1 row affected (0.00 sec)

mysql> select TIMESTAMPADD(WEEK, 1, time_test) from tt;
+----------------------------------+
| TIMESTAMPADD(WEEK, 1, time_test) |
+----------------------------------+
| 170:03:04                        |
+----------------------------------+
1 row in set (0.00 sec)
```

in stonedb-8.0, innodb & tianmu returns `2023-04-20 02:03:04`, the day execute this sql is `2023-04-13`.

### Expected behavior

The result in 5.7 is unreasonable, I think the sql layer has been modified. Make sure if it should be revert back.

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by hustjieke** [comment]
ping @chenshengjiang

**Comment by chenshengjiang** [comment]
AKA

**Comment by chenshengjiang** [comment]
ACK

**Comment by hustjieke** [comment]
Check the behaviour of original MySQL 5.7.

**Comment by chenshengjiang** [comment]
In the original MySQL5.7.42
```
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 5.7.42    |
+-----------+
1 row in set (0.00 sec)
```
the result is the same
```
mysql> select TIMESTAMPADD(WEEK, 1, time_test) from tt;
+----------------------------------+
| TIMESTAMPADD(WEEK, 1, time_test) |
+----------------------------------+
| 170:03:04                        |
+----------------------------------+
1 row in set (0.00 sec)
```
our MySQL version is 5.7.36, so it is a bug exiting in MySQL5.7, it has been solved in MySQL8.0
