### ISSUE TITLE
bug: bigint type, return wrong result;

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1564]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> create table t2 (x bigint not null);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t2(x) values (-16),(-15);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from t2;
+-----+
| x   |
+-----+
| -16 |
| -15 |
+-----+
2 rows in set (0.01 sec)

mysql> select * from t2 where x = 18446744073709551601;
+-----+
| x   |
+-----+
| -15 |
+-----+
1 row in set (0.00 sec)

```

### Expected behavior

```shelll
mysql> select * from t2 where x = 18446744073709551601;
Empty set (0.00 sec)
```

### Environment

```shell
root@ub01:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: d0665f9dc
        Last commit time: Date:   Wed Apr 12 10:52:39 2023 +0800
        Build time: Date: Wed Apr 12 19:37:30 CST 2023
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by hustjieke** [comment]
![image](https://github.com/stoneatom/stonedb/assets/18331104/2f420cce-1704-4ba2-97fe-209f0d255840)

**Comment by hustjieke** [comment]
ACK.

**Comment by hustjieke** [comment]
refs: https://stonedb.io/docs/SQL-reference/data-types

<p style="box-sizing: border-box; margin-right: ; margin-left: ; margin-bottom: var(--ifm-leading); margin-top: 0px; color: rgb(55, 60, 67); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following table provides the value range of each integer data type.</p>

Type | Storage (Bytes) | Minimum Value Signed | Minimum Value Unsigned | Maximum Value Signed | Maximum Value Unsigned
-- | -- | -- | -- | -- | --
TINYINT | 1 | -128 | 0 | 127 | 255
SMALLINT | 2 | -32768 | 0 | 32767 | 65535
MEDIUMINT | 3 | -8388608 | 0 | 8388607 | 16777215
INT | 4 | -2147483647 | 0 | 2147483647 | 4294967295
BIGINT | 8 | -9223372036854775806 | 0 | 9223372036854775807 | 9223372036854775807

<p style="box-sizing: border-box; margin-right: ; margin-left: ; margin-bottom: var(--ifm-leading); margin-top: 0px; color: rgb(55, 60, 67); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bolder;">Notice</strong>:</p><p style="box-sizing: border-box; margin-right: ; margin-left: ; margin-bottom: var(--ifm-leading); margin-top: 0px; color: rgb(55, 60, 67); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">INT</code><span> </span>type:<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">-2147483648</code><span> </span>is reserved to indicate<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">INT_NULL</code><span> </span>in<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">Tianmu</code><span> </span>engine,<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">Minimum Value Signed</code><span> </span>start from -2147483647.</p><p style="box-sizing: border-box; margin-right: ; margin-left: ; margin-bottom: var(--ifm-leading); margin-top: 0px; color: rgb(55, 60, 67); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">BIGINT</code><span> </span>type:<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">-9223372036854775807</code><span> </span>is reserved to indicate<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">BIGINT_NULL</code><span> </span>in<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">Tianmu</code>,<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">Maximum Value Signed</code><span> </span>start from -9223372036854775806.</p><p style="box-sizing: border-box; margin-right: ; margin-left: ; margin-bottom: var(--ifm-leading); margin-top: 0px; color: rgb(55, 60, 67); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For<span> </span><code style="box-sizing: border-box; vertical-align: middle; background-color: var(--ifm-code-background); border: 0.1rem solid rgba(0, 0, 0, 0.1); border-radius: var(--ifm-code-border-radius); font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; padding: var(--ifm-code-padding-vertical) var(--ifm-code-padding-horizontal);">BIGINT</code><span> </span>type: Maximum Value Unsigned currently limited to 9223372036854775807, we'll expand it to 18446744073709551615 in the future.</p>

**Comment by hustjieke** [comment]
For `bigint` in tianmu, ranges from `-9223372036854775806` to `9223372036854775807 `, `18446744073709551601` is a `uint64` value, but it can reinterpret to `int64` and the exact value is changed.

```
static_cast<int64_t>(18446744073709551601) = -15
```
