### ISSUE TITLE
question: sysbench benchmark possible? 

### ISSUE THREAD

**Issue by osevan** [stoneatom/stonedb#161]
Could you benchmark with sysbench and publish results? 

Thanks and

Best regards

**Comment by hustjieke** [comment]
> Could you benchmark wirh sysbench and publish results?
> 
> Thanks and
> 
> Best regards

Yeah, we are working on it, the results will be published once we finished benchmark.
Please look forward to it!

**Comment by osevan** [comment]
Could i benchmark already with sysbench is possible? 


If yes  i will tey today compile stonedb from source

**Comment by haitaoguan** [comment]
We have done the test of TPCH, you can read the report.
https://stonedb.io/docs/performance-tuning/performance-tests/OLAP/tcph-test-report

**Comment by RingsC** [comment]
As said above, you can find the test reports on our offical website pages. Therefore, we close it now, and feel free to reopen. 
Thanks.
