### ISSUE TITLE
docs: compile stoneDB in a docker container Chinese and English inconsistent

### ISSUE THREAD

**Issue by Dysprosium0626** [stoneatom/stonedb#1644]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Description

I'm trying to compile stonedb via Docker and refer to these two docs (one chinese version and one english version):
[Compile StoneDB in a Docker Container](https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-docker/)
[Docker 下编译使用 StoneDB](https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-docker)

However, finding that chinese version is not consistent with the english one in **Directly use StoneDB in the container**, 
the command line `./reinstall.sh` which is used to automatically deploy stonedb is missing in chinese ver.
![image](https://user-images.githubusercontent.com/59086724/235356685-7b540afd-8c4c-4637-97bb-b2d0a719459a.png)
![image](https://user-images.githubusercontent.com/59086724/235356727-7a415b9a-fe9b-4cf4-a584-6bf7b46a8212.png)

One more thing, I tried the `./reinstall.sh` after compiling the stonedb by cmake, and it will not work cuz the ABS_PATH is not defined in config file. Therefore, I tried the [manual deployment](https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-centos7/compile-using-centos7-for-57#step-5-start-stonedb) and it works. **So perhaps manual deployment is more friendly to newcomers?**

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Nliver** [comment]
Well, thank you very much for your feedback. We will check it carefully and get back to you later

**Comment by haitaoguan** [comment]
You can manually initialize and start the instance.If you start instance is failed, you need to look at tianmu.log.

**Comment by Dysprosium0626** [comment]
> You can manually initialize and start the instance.If you start instance is failed, you need to look at tianmu.log.

yes i mean i have have several ways to start the instance but the document is not the easiest way to start the stonedb. somehow it leads to some failure when i tried to deploy the stonedb step by step according to the command lines in the doc . I think the document need some modification...

**Comment by Nliver** [comment]
> > You can manually initialize and start the instance.If you start instance is failed, you need to look at tianmu.log.
> 
> yes i mean i have have several ways to start the instance but the document is not the easiest way to start the stonedb. somehow it leads to some failure when i tried to deploy the stonedb step by step according to the command lines in the doc . I think the document need some modification...

yes, of course, you are right. I fully understand your appeal. perhaps, could you please help to submit a PR to solve this problem? I will give you full help. as you know, we are eager to work with outside contributors to build StoneDB~

**Comment by Dysprosium0626** [comment]
> > > You can manually initialize and start the instance.If you start instance is failed, you need to look at tianmu.log.
> > 
> > 
> > yes i mean i have have several ways to start the instance but the document is not the easiest way to start the stonedb. somehow it leads to some failure when i tried to deploy the stonedb step by step according to the command lines in the doc . I think the document need some modification...
> 
> yes, of course, you are right. I fully understand your appeal. perhaps, could you please help to submit a PR to solve this problem? I will give you full help. as you know, we are eager to work with outside contributors to build StoneDB~

Sure, my pleasure. I have found a way to deploy stonedb by docker.
Should I summit a PR in the https://github.com/stoneatom/stonedb-docs repository?

**Comment by Nliver** [comment]
> > > > You can manually initialize and start the instance.If you start instance is failed, you need to look at tianmu.log.
> > > 
> > > 
> > > yes i mean i have have several ways to start the instance but the document is not the easiest way to start the stonedb. somehow it leads to some failure when i tried to deploy the stonedb step by step according to the command lines in the doc . I think the document need some modification...
> > 
> > 
> > yes, of course, you are right. I fully understand your appeal. perhaps, could you please help to submit a PR to solve this problem? I will give you full help. as you know, we are eager to work with outside contributors to build StoneDB~
> 
> Sure, my pleasure. I have found a way to deploy stonedb by docker. Should I summit a PR in the https://github.com/stoneatom/stonedb-docs repository?

Sorry, this document address of yours is not the latest at present. Our documents are currently in these two folders:
English document: https://github.com/stoneatom/stonedb/tree/stonedb-5.7-dev/Docs
Chinese document: https://github.com/stoneatom/stonedb/tree/stonedb-5.7-dev/website/i18n/zh/docusaurus-plugin-content-docs/current
Look forward to your contribution ~

**Comment by Dysprosium0626** [comment]
Already create PR, ready for review

**Comment by Nliver** [comment]
@Dysprosium0626 Thanks a lot~ we're going to review today
