### ISSUE TITLE
bug: Even if a primary key is defined, duplicate data may be imported.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1648]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> source /tmp/ttt.sql
......
mysql> show create table ttt\G
*************************** 1. row ***************************
       Table: sequence
Create Table: CREATE TABLE `ttt` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU AUTO_INCREMENT=3000000004910127 DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> select * from ttt where id=3000000000134587;
+------------------+---------------------+
| id               | created_date        |
+------------------+---------------------+
| 3000000000134587 | 2023-04-18 12:19:23 |
| 3000000000134587 | 2023-04-18 12:19:23 |
+------------------+---------------------+
2 rows in set (0.01 sec)

```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 57e3497
        Last commit time: Date:   Sat Apr 29 00:54:00 2023 +0800
        Build time: Date: Thu May  4 10:50:58 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by RingsC** [comment]
And do a test for setting the auto increment value to the boundary of data type to what will happen and more test cases should be considered. 
FIY: https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html

Pay more attention to the following scenarios:
1: Lock Mode;
2: increment value initalization
3: Crash Reconvery

**Comment by konghaiya** [comment]
The reason for duplicate imported data is due to deleting the data/. index directory before importing the data

**Comment by konghaiya** [comment]
After successfully installing stonedb, the reinstall.sh script needs to be used for initialization
