### ISSUE TITLE
backport:  EXPLAIN query Q4, MySQL server has gone away

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1666]
**Is your feature request related to a problem? Please describe.**

previous working issue: #727 
commit id: e61f3da1f7a323e4a0f981664fdfee58c189efb3

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
Check the code in 8.0, may be we had fix this bug.

**Comment by Xinqiangxu** [comment]
assigned me!

**Comment by xxq-xu** [comment]
this bug has fixed in stonedb-8.0-dev

**Comment by Xinqiangxu** [comment]
this bug has fixed in stonedb-8.0-dev
