### ISSUE TITLE
backport: rm duplicate 'lc-messages-dir' config item in my.cnf.sample

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1668]
**Is your feature request related to a problem? Please describe.**

previous working issue: #688
commit id: 5e86e93311896776b6c7a17b56ddafce06cb3fb7

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
check it in 8.0 if we had  fix it.

**Comment by chenshengjiang** [comment]
assigned me！
