### ISSUE TITLE
backport: support alter table xxx modify xxx type NULL/NOT NULL

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1671]
**Is your feature request related to a problem? Please describe.**

previous working issue: #860
commit id: d0c2e01b6e5c0ccca6cc0f6aa1a5568d7b08c3a6

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenshengjiang** [comment]
assigned me!
