### ISSUE TITLE
backport: support select ... where like null

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1677]
**Is your feature request related to a problem? Please describe.**

previous working issue: #763

related commit id:
- [x]  fadc2f2a23a6ab7c4643d2a6178133939772d74e
- [x] d75cbb5349ccd1eb3cd1f35030ff900a19d2bc85
- [x] 050a632d46c45d1ef074b45023399ba17abf7c47
- [x] 07c4869a12ec15f9aa42441aebde531533d6a71e
- [x] b3789e9aa3a3708b0e82f4e572d1857a3c274325
- [x] 08ac72f40f70a34ae38abd71c526366763196aba

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
fixed in [3393d9cf6929add1185647c696265534912f6c80](https://github.com/stoneatom/stonedb/commit/3393d9cf6929add1185647c696265534912f6c80)
