### ISSUE TITLE
backport: the EXTRACT() function error

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1691]
**Is your feature request related to a problem? Please describe.**

previous working issue: #845
commit id: 881f7139a175b1f3f2a2ef8d742a32844dd5a946

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Double0101** [comment]
When compile query in tianmu, in query_compile.cpp, the function VirtualColumnAlreadyExists() return incorrect value.
So it run into incorrect branch, mysql_expression remove the item in RemoveUnusedVarID();
```c++
int Query::AddColumnForMysqlExpression(MysqlExpression *mysql_expression, const TableID &tmp_table, const char *alias,
                                       const common::ColOperation oper, const bool distinct,
                                       bool group_by /*= false*/) {
  AttrID at, vc;
  vc.n = VirtualColumnAlreadyExists(tmp_table, mysql_expression);
  if (vc.n == common::NULL_VALUE_32) {
    cq->CreateVirtualColumn(vc, tmp_table, mysql_expression,
                            (oper == common::ColOperation::DELAYED ? tmp_table : TableID(common::NULL_VALUE_32)));
    tab_id2expression.insert(std::make_pair(tmp_table, std::make_pair(vc.n, mysql_expression)));
  } else {
    mysql_expression->RemoveUnusedVarID();
    ...
  }
}
```

**Comment by Double0101** [comment]
mysql_expression.cpp:
In operator== we should judge EXTRACT(DAY_HOUR FROM a) and EXTRACT(MINUTE_SECOND FROM b) unequal.
