### ISSUE TITLE
feature: unify code comments

### ISSUE THREAD

**Issue by hustjieke** [StoneAtom/stonedb#17]
**Is your feature request related to a problem? Please describe.**

Currently the comment in StoneDB is not unified: 
```
/*...*/
//
///
...
```

**Describe the solution you'd like**

For single line comment: `//`
For multi line comments: `/* .... */`

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
Follow google style: https://google.github.io/styleguide/cppguide.html#Comment_Style

**Comment by RingsC** [comment]
This is a part of #11 , therefore, firstly, we close this, and reopen it if necessary.
