### ISSUE TITLE
question: Illegal instruction on centos 7

### ISSUE THREAD

**Issue by gospider001** [stoneatom/stonedb#174]
![image](https://user-images.githubusercontent.com/35679142/177911105-64160cc4-62b1-40e5-9d35-2037720f343d.png)

## 按照官网快速部署教程，在centos7中部署，出现这个非法指令，不知道哪里出现了问题

**Comment by gospider001** [comment]
$ ldd mysqld
        linux-vdso.so.1 =>  (0x00007fff627cd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3ae83c6000)
        libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00007f3ae81c0000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3ae7fb0000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f3ae7da1000)
        libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f3ae7aee000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3ae78e6000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f3ae76af000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3ae74ab000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3ae71a9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3ae6ddb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3ae85e2000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3ae6ad3000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3ae68bd000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f3ae66ba000)

**Comment by RingsC** [comment]
Do you deploy the stonedb on virtual machine? If, yes, maybe, some instructions do not enable yet.

**Comment by RingsC** [comment]
you can refere to stonedb.io, to find out the answer in QA section.

**Comment by lylth** [comment]
When the instruction set of the installation environment lacks some key instruction sets of the compilation environment, running stonedb will report an "illegal instruction" error. It is recommended that you use the source code to compile and deploy in the running environment.

**Comment by gospider001** [comment]
好的😄

**Comment by RingsC** [comment]
@oldlwhite , Does the comment help you to fix your illegal instruction problem? Now, we close this issue, and feel free to reopen it again.
