### ISSUE TITLE
backport: support union query for fields whose data types are datetime and timestamp

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#1743]
**Is your feature request related to a problem? Please describe.**

working issue: #1114 

- [ ] commit id: 215161d0bad3a4f71d966aa1a425e29f14a1d6c0
- [ ] commit id: af1508f89e803f6930c10993bb21ee353f8d8e37
- [ ] commit id: 3fa2aab042e53a679b1045f98a646fc3a8bd05b9

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
related to #1690

**Comment by Double0101** [comment]
When set up the tmptable, in the function ColumnBinEncoder::EncoderDate::SecondColumn, it only return true when the vc->Type() is DATE. So it only can date union date or timestamp union timestamp;
```c++
bool ColumnBinEncoder::EncoderDate::SecondColumn(vcolumn::VirtualColumn *vc) {
  // Possible conversions: only dates.
  if (vc->Type().GetTypeName() != common::ColumnType::DATE) {
    tianmu_control_.lock(vc->ConnInfo()->GetThreadID())
        << "Nontrivial comparison: date with non-date" << system::unlock;
    return false;
  }
...
}
```
So we can use ATI::IsDateTimeType(type). Then not only type date return true, but alse datetime,timestamp etc return true.
