### ISSUE TITLE
bug:  当给decimal属性的字段赋值字符串默认值时， 在执行order by算子的时候导致崩溃

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1792]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
#0  0x00007f31944b3b7c in free () from /lib64/libc.so.6
#1  0x0000000001680daf in Tianmu::types::BString::~BString() ()
#2  0x0000000001680de2 in Tianmu::types::BString::~BString() ()
#3  0x000000000162501b in Tianmu::core::TempTable::OrderByAndMaterialize(std::vector<Tianmu::core::SortDescriptor, std::allocator<Tianmu::core::SortDescriptor> >&, long, long, Tianmu::core::ResultSender*) ()
#4  0x0000000001617534 in Tianmu::core::TempTable::Materialize(bool, Tianmu::core::ResultSender*, bool) ()
#5  0x00000000015e940e in Tianmu::core::Engine::Execute(THD*, LEX*, Query_result*, st_select_lex_unit*) ()
#6  0x00000000015ea0ea in Tianmu::core::Engine::HandleSelect(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int) ()
#7  0x00000000017efe70 in Tianmu::DBHandler::ha_my_tianmu_query(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int) ()
#8  0x0000000000fc14f8 in execute_sqlcom_select(THD*, TABLE_LIST*) ()
#9  0x0000000000fc8b13 in mysql_execute_command(THD*, bool) ()
#10 0x0000000000fcad35 in mysql_parse(THD*, Parser_state*) ()
#11 0x0000000000fcc339 in dispatch_command(THD*, COM_DATA const*, enum_server_command) ()
#12 0x0000000000fcd057 in do_command(THD*) ()
#13 0x0000000001085a48 in handle_connection ()
#14 0x000000000155cf84 in pfs_spawn_thread ()
#15 0x00007f3196ba5ea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f319452cb0d in clone () from /lib64/libc.so.6
```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: c3931fe
        Last commit time: Date:   Thu May 11 11:28:54 2023 +0800
        Build time: Date: Thu May 11 13:44:51 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by adofsauron** [comment]
客户的问题吧，还是得解决，不能拖着，放着不解决，那就让人认为是团队的态度问题。

所以还是要以客户第一，这个问题需要这么看:
当前的tianmu的查询树对于给不同数据类型的属性赋返回值在不同算子的实现。

脱离不开当前的查询树，此树对于与mysql方言的语法的兼容构成了问题，所以从这方面入手。

由于crash是P0级别的问题，所以在解决掉crash问题之后，再修正语法树导致的兼容性问题

**Comment by adofsauron** [comment]
由于涉及客户的数据，对应的复现过程不在这写，只记录问题的原因和分析，以作为记录之用。

**Comment by adofsauron** [comment]
由于是给客户相关的，不用英文记录了，毕竟也不是给别人做复现参考，但是得需要给客户看到进度

**Comment by adofsauron** [comment]
因为上边重要的记录被人删除了，为了追踪这个问题，将重要的分析记录做记录。
对于与mysql/innodb做100%兼容的事情，例如支持当前问题单的这个写法，是一种通用的问题，由于现在无论产品规划还是技术规划，既然没有明确的优先级，有没有需求的边界划分，所以这种写法的支持性是比是否要做这个事情更为重要的问题。
对于这个问题，兼容100%将导致难以想象的资源耗费。如果有这个资源可以投入的话，如果没有那就必须进行边界控制。
这个问题尤其重要，谁要是把这东西给删了，那就自己把这个100%的兼容性给解决出来!
