### ISSUE TITLE
feature: unify the variable naming style

### ISSUE THREAD

**Issue by hustjieke** [StoneAtom/stonedb#18]
**Is your feature request related to a problem? Please describe.**

The names of variables (including function parameters) and data members are all lowercase, with underscores between words. Data members of classes (but not structs) additionally have trailing underscores. For instance: a_local_variable, a_struct_data_member, a_class_data_member_.

**Describe the solution you'd like**

For example:
```
std::string table_name;  // OK - lowercase with underscore.
std::string tableName;   // Bad - mixed case.
```

```
class TableInfo {
  ...
 private:
  std::string table_name_;  // OK - underscore at end.
  static Pool<TableInfo>* pool_;  // OK.
};
```
...
...

**Describe alternatives you've considered**

**Additional context**

For more details: 
https://google.github.io/styleguide/cppguide.html#Variable_Names

**Comment by RingsC** [comment]
This issue classsified as clean code task, just as #11 does. Therefore, we close this, and reopen if necessary.
