### ISSUE TITLE
bug: github上的cicd上自动跑的MTR测试存在偶发的失败现象

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1810]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

https://github.com/stoneatom/stonedb/actions/runs/5022959617/jobs/9007804168

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by Nliver** [comment]
This issue already exists（#1803 #1800）, so without repeating it, I'm going to close this issue
