### ISSUE TITLE
which version can support  binog row format ?

### ISSUE THREAD

**Issue by GhostSubmarine** [stoneatom/stonedb#188]
which version can support mysql  binog row format

**Comment by zsp108** [comment]
Because the data organization of column-based storage is different from that of row-based storage, StoneDB currently supports only statement-based binlogs and we are working on the support for row-based binlogs. Once we finish the work, we will update the changelog. Thanks for your attention.

**Comment by RingsC** [comment]
@GhostSubmarine , Now, we have supported the row-based binlog, and You can check out the latest version to verify that. Hope you enjoy it. Thanks for your interest. 

Pls, feel free to reopen it again. Thanks.
