### ISSUE TITLE
question: git clone https://github.com/stoneatom/stonedb.git Prompt error RPC failed

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#189]
## General Question

【The environment】

- ubuntu 20.4
- stonedb for mysql5.7

【Problem description】
```
root@mstest01:/data# git clone https://github.com/stoneatom/stonedb.git
Cloning into 'stonedb'...
remote: Enumerating objects: 37712, done.
remote: Counting objects: 100% (362/362), done.
remote: Compressing objects: 100% (206/206), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
【The expected results】
This part is not mentioned in the "Installation document" in the introduction. It is suggested to supplement the solution to this problem in the introduction document to facilitate users to install StonedB quickly

**Comment by hustjieke** [comment]
This is related to network problem, check you network is normal or not.

**Comment by RingsC** [comment]
It is NOT an issue of STONEDB, so close it now.
