### ISSUE TITLE
bug: The instance is crashed if a table Inner joins constant queries

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1910]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> create table xxx(id int,name varchar(5));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into xxx values(1,'AAA'),(2,'BBB');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from xxx;
+------+------+
| id   | name |
+------+------+
|    1 | AAA  |
|    2 | BBB  |
+------+------+
2 rows in set (0.01 sec)

mysql> SELECT C.ud_type
    ->   FROM xxx A
    ->  INNER JOIN (SELECT '上划日' ud_type
    ->                FROM (SELECT @row1 := @row1 + 1 AS rowno FROM (SELECT 0) t1) a) C
    ->     ON 1 = 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### How To Reproduce

./mysqld  Ver 5.7.36-StoneDB-v1.0.1 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: a4600c4
        Last commit time: Date:   Thu Jun 15 21:10:49 2023 +0800
        Build time: Date: Tue Jun 27 01:17:55 UTC 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by Xinqiangxu** [comment]
The reasons for crash are as follows:
In `query.cpp`, when we need to create a temp table by using function `ta[-step.t1.n - 1] = TempTable::Create(ta[-step.tables1[0].n - 1].get(), step.tables1[0].n, this, sub_type)`, the parameter `ta[-step.tables1[0].n - 1].get()` would be null if  `-step.tables1[0].n - 1` is equal to `-step.t1.n - 1`. 
At the same time, this will cause the result_temptable's attribute `materialized` to be true, which leads to crash.

**Comment by haitaoguan** [comment]
###tianmu
+-----------+
| ud_type   |
+-----------+
| 上划日    |
| 上划日    |
+-----------+

###InnoDB
+-----------+
| ud_type   |
+-----------+
| 上划日    |
+-----------+
