### ISSUE TITLE
bug: ERROR 1105 (HY000): assert failed on cur_pack != nullptr at tianmu_attr.cpp:427, msg: [Pack ptr is null]

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1912]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
mysql> SELECT IFNULL(b.CURRENCY_NAME, '合计（人民币）') CURRENCY_NAME
    ->   FROM v_c1am_busi_type a
    ->   LEFT JOIN (select a.INNER_CODE, a.CURRENCY_ID, d.CURRENCY_NAME
    ->                FROM (SELECT a.INNER_CODE, b.CURRENCY_ID
    ->                        FROM v_c1am_busi_type a
    ->                       CROSS JOIN (SELECT a.TENANT_ID, b.CURRENCY_ID
    ->                                    FROM C1AM_BANK_CLASS a, c1AM_BANK_LIST b
    ->                                   where a.SERIAL_ID = b.ROW_ID
    ->                                     and F_DATE_FORMAT(b.TRADE_DATE) BETWEEN
    ->                                         DATE_FORMAT('2023-06-06', '%Y-%m-%d') AND
    ->                                         DATE_FORMAT('2023-06-06', '%Y-%m-%d')
    ->                                   GROUP BY a.TENANT_ID, b.CURRENCY_ID) b
    ->                       WHERE a.CLASS_ID = 3000000000233027) a
    ->                LEFT JOIN C1CD_CURRENCY d
    ->                  ON a.CURRENCY_ID = d.ROW_ID) b
    ->     ON a.INNER_CODE =
    ->   LEFT(b.INNER_CODE, LENGTH(a.INNER_CODE))
    ->  GROUP BY b.CURRENCY_NAME;
ERROR 1105 (HY000): assert failed on cur_pack != nullptr at tianmu_attr.cpp:427, msg: [Pack ptr is null]
```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.1 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: a4600c4
        Last commit time: Date:   Thu Jun 15 21:10:49 2023 +0800
        Build time: Date: Tue Jun 27 01:17:55 UTC 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by RingsC** [comment]
@Xinqiangxu , pls, check it out.
