### ISSUE TITLE
bug: docker image stoneatom/stonedb:v1.0.4 is too large, is this expected?

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [stoneatom/stonedb#1923]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

## For stoneatom/stonedb:v1.0.4, tested in GitHub Codespace
The size of docker image stoneatom/stonedb:v1.0.4 after deCOMPRESStion is too large, e.g. more than 19GB, I am not sure if this is expected so creating this issue for reference?

This image decirbe when extrating `94e9177159f2:`, my available space drop from 19GB to 0GB.

![image](https://github.com/stoneatom/stonedb/assets/63448884/21e9ef79-e33b-4465-babe-030f86463d3b)

### For stoneatom/stonedb:v1.0.4, tested in GitHub Action

we can see just after running single docker pull command, space drop from 60GB to 24GB.

<img width="1263" alt="image" src="https://github.com/stoneatom/stonedb/assets/63448884/858d8b9f-0a60-429b-9732-e70d1a90a490">

## For stoneatom/stonedb:v1.0.3
However, if I use docker image stoneatom/stonedb:v1.0.3, it just take 2 GB, from 19GB to 17GB:
<img width="1043" alt="image" src="https://github.com/stoneatom/stonedb/assets/63448884/38ede94f-cadf-4d2a-ab7d-d017c6c05ae7">

### Expected behavior

I think it should not be larger than 19GB. 

Maybe the size of `docker image stoneatom/stonedb:v1.0.3`, which is about 2GB, is more appropriate.

### How To Reproduce

docker pull stoneatom/stonedb:v1.0.4

### Environment

Gihub Codespace

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by Nliver** [comment]
@ZhengLin-Li  Thank you very much. We already know about this problem and are investigating it

**Comment by chenshengjiang** [comment]
The size of docker image `stoneatom/stonedb:v1.0.4` pulled from dockerhub is 35.7G which is abnormal. I find it is because the parameter `tianmu_hugefilesize` in my.cnf has been set to `30720` euqals `30.7G`, so it will take 30.7G mem when mysqld starts.

In the process of docker build image, somehow mysqld starts after executing `rpm -ivh --force /opt/resource/rpm/*.rpm`,  so the size of this layer is more than `30G`. I think maybe mysqld is still running when packing stonedb. 

It is necessary to make `tianmu_hugefilesize` smaller and repack stonedb.

**Comment by Nliver** [comment]
@ZhengLin-Li hello, we have updated the image of Dcoker, the problem should be solved, you can try the latest image package, I will close this issue later~

https://hub.docker.com/r/stoneatom/stonedb/tags

```
docker pull stoneatom/stonedb:v1.0.4
```
