### ISSUE TITLE
crash: StoneDB crash when executing the command (SELECT, HAING, GROUP BY, IS NULL)

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [stoneatom/stonedb#1941]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

SQLancer find that StoneDB will crash when executing the command:
```sql
SELECT *
FROM t0
GROUP BY t0.c0
HAVING (t0.c0 IS NULL)
UNION ALL
SELECT *
FROM t0
GROUP BY t0.c0
HAVING (NOT (t0.c0 IS NULL))
UNION ALL
SELECT *
FROM t0
GROUP BY t0.c0
HAVING (((t0.c0 IS NULL)) IS NULL);
```

![image](https://github.com/stoneatom/stonedb/assets/63448884/95e45124-91dd-4727-a271-395014718504)

### Expected behavior

will not crash and return empty set

### How To Reproduce

```sql
drop database db100;
create database db100;
use db100;
create table t0 (c0 int);

SELECT *
FROM t0
GROUP BY t0.c0
HAVING (t0.c0 IS NULL)
UNION ALL
SELECT *
FROM t0
GROUP BY t0.c0
HAVING (NOT (t0.c0 IS NULL))
UNION ALL
SELECT *
FROM t0
GROUP BY t0.c0
HAVING (((t0.c0 IS NULL)) IS NULL);
```

### Environment

docker latest version

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by haitaoguan** [comment]
![image](https://github.com/stoneatom/stonedb/assets/105625912/0f267bdc-4dca-4094-883f-7e2fdbb33230)

./mysqld  Ver 5.7.36-StoneDB-v1.0.4 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 2bb2d48
        Last commit time: Date:   Thu Jul 13 10:04:56 2023 +0800
        Build time: Date: Thu Jul 13 02:11:43 UTC 2023

**Comment by zhenglin-charlie-li** [comment]
@haitaoguan So, it means that this issue has been fixed? If so, maybe we can close this issue.
