### ISSUE TITLE
bug: query result not correct

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [stoneatom/stonedb#1942]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

SQLancer found that the query below result is not correct on docker v1.0.4, though correct result on docker v1.0.3

![image](https://github.com/stoneatom/stonedb/assets/63448884/f7f47ca3-be4e-46f6-8bbd-4f21672142e6)

### Expected behavior

both two select return `NULL`

### How To Reproduce

```sql
CREATE TABLE t0(c0 INT);
SELECT * FROM t0 WHERE (t0.c0 IS NULL); 
SELECT SUM(count) FROM (SELECT (t0.c0 IS NULL) IS TRUE  as count FROM t0) as res; -- Expted NULL but got 1
SELECT SUM(count) FROM (SELECT CAST((t0.c0 IS NULL) AS UNSIGNED)  as count FROM t0) as res;  -- Expted NULL but got 1
```

### Environment

docker v1.0.4

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by Double0101** [comment]
In the function `AggregationAlgorithm::Aggregate` in aggregation_algorithm.cpp, it doesn't check validity of `mit` before `PutAggregatedValue`.
```c++
void AggregationAlgorithm::Aggregate(bool just_distinct, int64_t &limit, int64_t &offset, ResultSender *sender) {
  MEASURE_FET("TempTable::Aggregate(...)");
  thd_proc_info(m_conn->Thd(), "aggregation");
......
  {
      for (int gr_a = gbw.NumOfGroupingAttrs(); gr_a < gbw.NumOfAttrs(); gr_a++) {
        TempTable::Attr &cur_a = *(t->GetAttrP(gr_a));

        if (cur_a.term.vc && dynamic_cast<Tianmu::vcolumn::ExpressionColumn *>(cur_a.term.vc)) {
          bool value_successfully_aggregated = gbw.PutAggregatedValue(gr_a, 0, mit, mit.Factor());
          if (!value_successfully_aggregated) {
            gbw.DistinctlyOmitted(gr_a, 0);
          }
        }
      }
    }
  } 
......
}
```
