### ISSUE TITLE
bug: 5.7 compile error

### ISSUE THREAD

**Issue by shawn0915** [stoneatom/stonedb#1968]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
Consolidate compiler generated dependencies of target mysqld
[100%] Linking CXX executable mysqld
/bin/ld: ../archive_output_directory/libtianmu.a(merge_operator.cpp.o):(.data.rel.ro._ZTIN6Tianmu4core19RecordMergeOperatorE[_ZTIN6Tianmu4core19RecordMergeOperatorE]+0x10): undefined reference to `typeinfo for rocksdb::AssociativeMergeOperator'
collect2: error: ld returned 1 exit status
make[2]: *** [sql/CMakeFiles/mysqld.dir/build.make:129: sql/mysqld] Error 1
make[1]: *** [CMakeFiles/Makefile2:5589: sql/CMakeFiles/mysqld.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
[shawnyan@rocky9 release]$
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by Nliver** [comment]
@shawn0915  What is your deployment environment? Could you please provide more information?
