### ISSUE TITLE
bug: stonedb5.7 on centos7.9 run mtr tests fail

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#209]
### Describe the problem

http://192.168.30.238:8080/job/stonedb5.7-zsl-centos7.9/10/execution/node/71/log/

https://gitee.com/adofsuaron/stonedb-dev/blob/stonedb-5.7/.jenkins/jenkinsfile-stonedb5.7-centos7.9

`

                    cd /stonedb57/install/mysql-test
                    sudo ./mysql-test-run.pl --suite=stonedb --nowarnings --force

`

`
+ JENKINS_NODE_COOKIE=dontKillMe
+ export JENKINS_NODE_COOKIE=dontKillMe
+ JENKINS_NODE_COOKIE=dontKillMe
+ cd /stonedb57/install/mysql-test
+ sudo ./mysql-test-run.pl --suite=stonedb --nowarnings --force
Logging: ./mysql-test-run.pl  --suite=stonedb --nowarnings --force
MySQL Version 5.7.36
Checking supported features...
 - SSL connections supported
 - binaries are debug compiled
Using suites: stonedb
Collecting tests...
Removing old var directory...
Creating var directory '/data/stonedb57/install/mysql-test/var'...
Installing system database...
Using parallel: 1

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
worker[1] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
[  3%] stonedb.add_column                       [ fail ]
        Test ended at 2022-07-13 13:11:30

CURRENT_TEST: stonedb.add_column
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/add_column.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/add_column.reject	2022-07-13 08:11:29.858000000 +0300
@@ -48,5 +48,5 @@
 values(105,105,105,105,105,5.2,10.88,105.083,'2016-02-25','2016-02-25 10:20:01','2016-02-25 05:20:01','10:20:01','stoneatom','hello','bcdefghijklmn',105);
 select count(*) from column_type_test;
 count(*)
-100001
+100000
 drop table column_type_test;

mysqltest: Result content mismatch

safe_process[8955]: Child process: 8956, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.add_column/add_column.log'

Retrying test stonedb.add_column, attempt(2/3)...

[  3%] stonedb.add_column                       [ retry-fail ]
        Test ended at 2022-07-13 13:11:36

CURRENT_TEST: stonedb.add_column
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/add_column.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/add_column.reject	2022-07-13 08:11:36.302000000 +0300
@@ -48,5 +48,5 @@
 values(105,105,105,105,105,5.2,10.88,105.083,'2016-02-25','2016-02-25 10:20:01','2016-02-25 05:20:01','10:20:01','stoneatom','hello','bcdefghijklmn',105);
 select count(*) from column_type_test;
 count(*)
-100001
+100000
 drop table column_type_test;

mysqltest: Result content mismatch

safe_process[9233]: Child process: 9234, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.add_column/add_column.log'

Test stonedb.add_column has failed 2 times, no more retries!

[  6%] stonedb.casewhen                         [ pass ]     51

MTR's internal check of the test case 'stonedb.casewhen' failed.
This means that the test case does not preserve the state that existed
before the test case was executed.  Most likely the test case did not
do a proper clean-up. It could also be caused by the previous test run
by this thread, if the server wasn't restarted.
This is the diff of the states of the servers before and after the
test case was executed:
mysqltest: Logging to '/data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.log'.
mysqltest: Results saved in '/data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result'.
mysqltest: Connecting to server localhost:13000 (socket /data/stonedb57/install/mysql-test/var/tmp/mysqld.1.sock) as 'root', connection 'default', attempt 0 ...
mysqltest: ... Connected.
mysqltest: Start processing test commands from './include/check-testcase.test' ...
mysqltest: ... Done processing test commands.
Binary files /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result and /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.reject differ

The two files differ but it was not possible to execute 'diff' in
order to show only the difference. Instead the whole content of the
two files was shown for you to diff manually.

To get a better report you should install 'diff' on your system, which you
for example can get from http://www.gnu.org/software/diffutils/diffutils.html

 --- /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result >>>
Slave_IO_State	
Master_Host	127.0.0.1
Master_User	root
Master_Port	#
Connect_Retry	#
Master_Log_File	#
Read_Master_Log_Pos	#
Relay_Log_File	#
Relay_Log_Pos	#
Relay_Master_Log_File	#
Slave_IO_Running	No
Slave_SQL_Running	No
Replicate_Do_DB	#
Replicate_Ignore_DB	#
Replicate_Do_Table	#
Replicate_Ignore_Table	#
Replicate_Wild_Do_Table	#
Replicate_Wild_Ignore_Table	#
Last_Errno	0
Last_Error	
Skip_Counter	0
Exec_Master_Log_Pos	#
Relay_Log_Space	#
Until_Condition	#
Until_Log_File	#
Until_Log_Pos	#
Master_SSL_Allowed	No
Master_SSL_CA_File	
Master_SSL_CA_Path	
Master_SSL_Cert	
Master_SSL_Cipher	
Master_SSL_Key	
Seconds_Behind_Master	NULL
Master_SSL_Verify_Server_Cert	No
Last_IO_Errno	0
Last_IO_Error	
Last_SQL_Errno	0
Last_SQL_Error	
Replicate_Ignore_Server_Ids	
Master_Server_Id	#
Master_UUID	#
Master_Info_File	#
SQL_Delay	0
SQL_Remaining_Delay	NULL
Slave_SQL_Running_State	
Master_Retry_Count	#
Master_Bind	
Last_IO_Error_Timestamp	
Last_SQL_Error_Timestamp	
Master_SSL_Crl	
Master_SSL_Crlpath	
Retrieved_Gtid_Set	#
Executed_Gtid_Set	#
Auto_Position	0
Replicate_Rewrite_DB	#
Channel_Name	#
Master_TLS_Version	
NAME	ENABLED	TIMED
NAME	ENABLED
events_stages_current	YES
events_stages_history	YES
events_stages_history_long	YES
events_statements_current	YES
events_statements_history	YES
events_statements_history_long	YES
events_transactions_current	YES
events_transactions_history	YES
events_transactions_history_long	YES
events_waits_current	YES
events_waits_history	YES
events_waits_history_long	YES
global_instrumentation	YES
statements_digest	YES
thread_instrumentation	YES
HOST	USER	ROLE	ENABLED	HISTORY
%	%	%	YES	YES
OBJECT_TYPE	OBJECT_SCHEMA	OBJECT_NAME	ENABLED	TIMED
EVENT	%	%	YES	YES
EVENT	information_schema	%	NO	NO
EVENT	mysql	%	NO	NO
EVENT	performance_schema	%	NO	NO
EVENT	sys_stonedb
mysqltest: Result content mismatch

not ok
safe_process[9514]: Child process: 9515, exit: 1

[ 10%] stonedb.concat                           [ fail ]
        Test ended at 2022-07-13 13:11:49

CURRENT_TEST: stonedb.concat
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/concat.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/concat.reject	2022-07-13 08:11:48.982000000 +0300
@@ -8,7 +8,4 @@
 insert into test_case values(3,'test3');
 select concat(id,name) from test_case;
 concat(id,name)
-1test
-NULL
-3test3
 drop table test_case;

mysqltest: Result length mismatch

safe_process[9801]: Child process: 9802, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.concat/concat.log'

Retrying test stonedb.concat, attempt(2/3)...

[ 10%] stonedb.concat                           [ retry-fail ]
        Test ended at 2022-07-13 13:11:52

CURRENT_TEST: stonedb.concat
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/concat.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/concat.reject	2022-07-13 08:11:51.945000000 +0300
@@ -8,7 +8,4 @@
 insert into test_case values(3,'test3');
 select concat(id,name) from test_case;
 concat(id,name)
-1test
-NULL
-3test3
 drop table test_case;

mysqltest: Result length mismatch

safe_process[10033]: Child process: 10034, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.concat/concat.log'

Test stonedb.concat has failed 2 times, no more retries!

[ 13%] stonedb.drop_column                      [ pass ]    141

MTR's internal check of the test case 'stonedb.drop_column' failed.
This means that the test case does not preserve the state that existed
before the test case was executed.  Most likely the test case did not
do a proper clean-up. It could also be caused by the previous test run
by this thread, if the server wasn't restarted.
This is the diff of the states of the servers before and after the
test case was executed:
mysqltest: Logging to '/data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.log'.
mysqltest: Results saved in '/data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result'.
mysqltest: Connecting to server localhost:13000 (socket /data/stonedb57/install/mysql-test/var/tmp/mysqld.1.sock) as 'root', connection 'default', attempt 0 ...
mysqltest: ... Connected.
mysqltest: Start processing test commands from './include/check-testcase.test' ...
mysqltest: ... Done processing test commands.
Binary files /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result and /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.reject differ

The two files differ but it was not possible to execute 'diff' in
order to show only the difference. Instead the whole content of the
two files was shown for you to diff manually.

To get a better report you should install 'diff' on your system, which you
for example can get from http://www.gnu.org/software/diffutils/diffutils.html

 --- /data/stonedb57/install/mysql-test/var/tmp/check-mysqld_1.result >>>
Slave_IO_State	
Master_Host	127.0.0.1
Master_User	root
Master_Port	#
Connect_Retry	#
Master_Log_File	#
Read_Master_Log_Pos	#
Relay_Log_File	#
Relay_Log_Pos	#
Relay_Master_Log_File	#
Slave_IO_Running	No
Slave_SQL_Running	No
Replicate_Do_DB	#
Replicate_Ignore_DB	#
Replicate_Do_Table	#
Replicate_Ignore_Table	#
Replicate_Wild_Do_Table	#
Replicate_Wild_Ignore_Table	#
Last_Errno	0
Last_Error	
Skip_Counter	0
Exec_Master_Log_Pos	#
Relay_Log_Space	#
Until_Condition	#
Until_Log_File	#
Until_Log_Pos	#
Master_SSL_Allowed	No
Master_SSL_CA_File	
Master_SSL_CA_Path	
Master_SSL_Cert	
Master_SSL_Cipher	
Master_SSL_Key	
Seconds_Behind_Master	NULL
Master_SSL_Verify_Server_Cert	No
Last_IO_Errno	0
Last_IO_Error	
Last_SQL_Errno	0
Last_SQL_Error	
Replicate_Ignore_Server_Ids	
Master_Server_Id	#
Master_UUID	#
Master_Info_File	#
SQL_Delay	0
SQL_Remaining_Delay	NULL
Slave_SQL_Running_State	
Master_Retry_Count	#
Master_Bind	
Last_IO_Error_Timestamp	
Last_SQL_Error_Timestamp	
Master_SSL_Crl	
Master_SSL_Crlpath	
Retrieved_Gtid_Set	#
Executed_Gtid_Set	#
Auto_Position	0
Replicate_Rewrite_DB	#
Channel_Name	#
Master_TLS_Version	
NAME	ENABLED	TIMED
NAME	ENABLED
events_stages_current	YES
events_stages_history	YES
events_stages_history_long	YES
events_statements_current	YES
events_statements_history	YES
events_statements_history_long	YES
events_transactions_current	YES
events_transactions_history	YES
events_transactions_history_long	YES
events_waits_current	YES
events_waits_history	YES
events_waits_history_long	YES
global_instrumentation	YES
statements_digest	YES
thread_instrumentation	YES
HOST	USER	ROLE	ENABLED	HISTORY
%	%	%	YES	YES
OBJECT_TYPE	OBJECT_SCHEMA	OBJECT_NAME	ENABLED	TIMED
EVENT	%	%	YES	YES
EVENT	information_schema	%	NO	NO
EVENT	mysql	%	NO	NO
EVENT	performance_schema	%	NO	NO
EVENT	sys_stonedb
mysqltest: Result content mismatch

not ok
safe_process[10271]: Child process: 10272, exit: 1

[ 16%] stonedb.group_concat                     [ fail ]
        Test ended at 2022-07-13 13:12:04

CURRENT_TEST: stonedb.group_concat
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/group_concat.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/group_concat.reject	2022-07-13 08:12:04.359000000 +0300
@@ -11,27 +11,12 @@
 insert into test_groupconcat_case values(2,'test2');
 select id,group_concat(name SEPARATOR ",") from test_groupconcat_case group by id;
 id	group_concat(name SEPARATOR ",")
-1	test,test1,test1
-2	test,test2
-3	test1
 select id,group_concat(name SEPARATOR ",") from test_groupconcat_case group by id order by id desc;
 id	group_concat(name SEPARATOR ",")
-3	test1
-2	test,test2
-1	test,test1,test1
 select id,group_concat(name SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(name SEPARATOR ":")
-1	test:test1:test1
-2	test:test2
-3	test1
 select id,group_concat(name order by name desc SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(name order by name desc SEPARATOR ":")
-1	test1:test1:test
-2	test2:test
-3	test1
 select id,group_concat(distinct name SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(distinct name SEPARATOR ":")
-1	test:test1
-2	test:test2
-3	test1
 drop table test_groupconcat_case;

mysqltest: Result content mismatch

safe_process[10561]: Child process: 10562, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.group_concat/group_concat.log'

Retrying test stonedb.group_concat, attempt(2/3)...

[ 16%] stonedb.group_concat                     [ retry-fail ]
        Test ended at 2022-07-13 13:12:07

CURRENT_TEST: stonedb.group_concat
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/group_concat.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/group_concat.reject	2022-07-13 08:12:07.519000000 +0300
@@ -11,27 +11,12 @@
 insert into test_groupconcat_case values(2,'test2');
 select id,group_concat(name SEPARATOR ",") from test_groupconcat_case group by id;
 id	group_concat(name SEPARATOR ",")
-1	test,test1,test1
-2	test,test2
-3	test1
 select id,group_concat(name SEPARATOR ",") from test_groupconcat_case group by id order by id desc;
 id	group_concat(name SEPARATOR ",")
-3	test1
-2	test,test2
-1	test,test1,test1
 select id,group_concat(name SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(name SEPARATOR ":")
-1	test:test1:test1
-2	test:test2
-3	test1
 select id,group_concat(name order by name desc SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(name order by name desc SEPARATOR ":")
-1	test1:test1:test
-2	test2:test
-3	test1
 select id,group_concat(distinct name SEPARATOR ":") from test_groupconcat_case group by id;
 id	group_concat(distinct name SEPARATOR ":")
-1	test:test1
-2	test:test2
-3	test1
 drop table test_groupconcat_case;

mysqltest: Result content mismatch

safe_process[10803]: Child process: 10804, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.group_concat/group_concat.log'

Test stonedb.group_concat has failed 2 times, no more retries!

[ 20%] stonedb.group_concat2                    [ fail ]
        Test ended at 2022-07-13 13:12:10

CURRENT_TEST: stonedb.group_concat2
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/group_concat2.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/group_concat2.reject	2022-07-13 08:12:10.391000000 +0300
@@ -7,8 +7,6 @@
 insert into test_groupconcat2_case values(1, 4);
 select id,group_concat(val order by val desc SEPARATOR " ") from test_groupconcat2_case group by id;
 id	group_concat(val order by val desc SEPARATOR " ")
-1	22 4
 select id,group_concat(distinct val SEPARATOR ":") from test_groupconcat2_case group by id;
 id	group_concat(distinct val SEPARATOR ":")
-1	22:4
 drop table test_groupconcat2_case;

mysqltest: Result content mismatch

safe_process[11031]: Child process: 11032, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.group_concat2/group_concat2.log'

Retrying test stonedb.group_concat2, attempt(2/3)...

[ 20%] stonedb.group_concat2                    [ retry-fail ]
        Test ended at 2022-07-13 13:12:13

CURRENT_TEST: stonedb.group_concat2
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/group_concat2.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/group_concat2.reject	2022-07-13 08:12:13.295000000 +0300
@@ -7,8 +7,6 @@
 insert into test_groupconcat2_case values(1, 4);
 select id,group_concat(val order by val desc SEPARATOR " ") from test_groupconcat2_case group by id;
 id	group_concat(val order by val desc SEPARATOR " ")
-1	22 4
 select id,group_concat(distinct val SEPARATOR ":") from test_groupconcat2_case group by id;
 id	group_concat(distinct val SEPARATOR ":")
-1	22:4
 drop table test_groupconcat2_case;

mysqltest: Result content mismatch

safe_process[11273]: Child process: 11274, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.group_concat2/group_concat2.log'

Test stonedb.group_concat2 has failed 2 times, no more retries!

[ 23%] stonedb.insert                           [ fail ]
        Test ended at 2022-07-13 13:12:16

CURRENT_TEST: stonedb.insert
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/insert.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/insert.reject	2022-07-13 08:12:16.322000000 +0300
@@ -30,9 +30,4 @@
 values(104,104,104,104,104,5.2,10.88,104.083,'2016-02-25','2016-02-25 10:20:01','2016-02-25 05:20:01','10:20:01','stoneatom','hello','bcdefghijklmn');
 select * from column_type_test;
 c_tinyint	c_smallint	c_mediumint	c_int	c_bigint	c_float	c_double	c_decimal	c_date	c_datetime	c_timestamp	c_time	c_char	c_varchar	c_blob	c_text	c_longblob
-100	100	100	100	100	5.2	10.88	100.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-101	101	101	101	101	5.2	10.88	101.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-102	102	102	102	102	5.2	10.88	102.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-103	103	103	103	103	5.2	10.88	103.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-104	104	104	104	104	5.2	10.88	104.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
 drop table column_type_test;

mysqltest: Result length mismatch

safe_process[11500]: Child process: 11501, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.insert/insert.log'

Retrying test stonedb.insert, attempt(2/3)...

[ 23%] stonedb.insert                           [ retry-fail ]
        Test ended at 2022-07-13 13:12:19

CURRENT_TEST: stonedb.insert
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/insert.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/insert.reject	2022-07-13 08:12:19.476000000 +0300
@@ -30,9 +30,4 @@
 values(104,104,104,104,104,5.2,10.88,104.083,'2016-02-25','2016-02-25 10:20:01','2016-02-25 05:20:01','10:20:01','stoneatom','hello','bcdefghijklmn');
 select * from column_type_test;
 c_tinyint	c_smallint	c_mediumint	c_int	c_bigint	c_float	c_double	c_decimal	c_date	c_datetime	c_timestamp	c_time	c_char	c_varchar	c_blob	c_text	c_longblob
-100	100	100	100	100	5.2	10.88	100.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-101	101	101	101	101	5.2	10.88	101.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-102	102	102	102	102	5.2	10.88	102.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-103	103	103	103	103	5.2	10.88	103.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
-104	104	104	104	104	5.2	10.88	104.08300	2016-02-25	2016-02-25 10:20:01	2016-02-25 05:20:01	10:20:01	stoneatom	hello	NULL	bcdefghijklmn	NULL
 drop table column_type_test;

mysqltest: Result length mismatch

safe_process[11731]: Child process: 11732, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.insert/insert.log'

Test stonedb.insert has failed 2 times, no more retries!

[ 26%] stonedb.issue405                         [ fail ]
        Test ended at 2022-07-13 13:12:22

CURRENT_TEST: stonedb.issue405
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/issue405.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/issue405.reject	2022-07-13 08:12:22.319000000 +0300
@@ -3,6 +3,4 @@
 insert into timehi values ('00:00:00'), ('01:15:39'), ('09:11:12'), ('20:30:29');
 select * from timehi where val >= '08:02:45';
 val
-09:11:12
-20:30:29
 drop table timehi;

mysqltest: Result length mismatch

safe_process[11949]: Child process: 11950, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue405/issue405.log'

Retrying test stonedb.issue405, attempt(2/3)...

[ 26%] stonedb.issue405                         [ retry-fail ]
        Test ended at 2022-07-13 13:12:25

CURRENT_TEST: stonedb.issue405
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/issue405.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/issue405.reject	2022-07-13 08:12:25.431000000 +0300
@@ -3,6 +3,4 @@
 insert into timehi values ('00:00:00'), ('01:15:39'), ('09:11:12'), ('20:30:29');
 select * from timehi where val >= '08:02:45';
 val
-09:11:12
-20:30:29
 drop table timehi;

mysqltest: Result length mismatch

safe_process[12190]: Child process: 12191, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue405/issue405.log'

Test stonedb.issue405 has failed 2 times, no more retries!

[ 30%] stonedb.issue410                         [ fail ]
        Test ended at 2022-07-13 13:12:28

CURRENT_TEST: stonedb.issue410
mysqltest: At line 4: query 'select * from tlike where val like NULL' failed: 6: The query includes syntax that is not supported by the storage engine. Either restructure the query with supported syntax, or enable the MySQL core::Query Path in config file to execute the query with reduced performance.

The result from queries just before the failure was:
use test;
create table tlike (val varchar(255)) ENGINE=STONEDB;
insert into tlike values ('abcde');
safe_process[12429]: Child process: 12430, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue410/issue410.log'

Retrying test stonedb.issue410, attempt(2/3)...

[ 30%] stonedb.issue410                         [ retry-fail ]
        Test ended at 2022-07-13 13:12:31

CURRENT_TEST: stonedb.issue410
mysqltest: At line 4: query 'select * from tlike where val like NULL' failed: 6: The query includes syntax that is not supported by the storage engine. Either restructure the query with supported syntax, or enable the MySQL core::Query Path in config file to execute the query with reduced performance.

The result from queries just before the failure was:
use test;
create table tlike (val varchar(255)) ENGINE=STONEDB;
insert into tlike values ('abcde');
safe_process[12654]: Child process: 12655, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue410/issue410.log'

Test stonedb.issue410 has failed 2 times, no more retries!

[ 33%] stonedb.issue415                         [ fail ]
        Test ended at 2022-07-13 13:12:34

CURRENT_TEST: stonedb.issue415
mysqltest: At line 21: query 'insert into select_base_with_primary_key values (11, 'abcde', 123, 'char', 3, 1, 23, 32, 332, 1.4, 25, '2017-11-11', '11:11:11', '2017-11-11 11:11:11', 1, 2017)' failed: 1292: Incorrect datetime value: '1' for column 'timestamp_test' at row 1

The result from queries just before the failure was:
use test;
CREATE TABLE `select_base_with_primary_key` (
`pk` bigint(11) NOT NULL AUTO_INCREMENT,
`varchar_test` varchar(255) DEFAULT NULL,
`integer_test` int(11) DEFAULT NULL,
`char_test` char(255) DEFAULT NULL,
`tinyint_test` tinyint(4) DEFAULT NULL,
`tinyint_1bit_test` tinyint(1) DEFAULT NULL,
`smallint_test` smallint(6) DEFAULT NULL,
`mediumint_test` mediumint(9) DEFAULT NULL,
`bigint_test` bigint(20) DEFAULT NULL,
`double_test` double DEFAULT NULL,
`decimal_test` decimal(10,0) DEFAULT NULL,
`date_test` date DEFAULT NULL,
`time_test` time DEFAULT NULL,
`datetime_test` datetime DEFAULT NULL,
`timestamp_test` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`year_test` year(4) DEFAULT NULL,
PRIMARY KEY (`pk`)
) ENGINE=STONEDB DEFAULT CHARSET=gbk;
safe_process[12890]: Child process: 12891, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue415/issue415.log'

Retrying test stonedb.issue415, attempt(2/3)...

[ 33%] stonedb.issue415                         [ retry-fail ]
        Test ended at 2022-07-13 13:12:37

CURRENT_TEST: stonedb.issue415
mysqltest: At line 21: query 'insert into select_base_with_primary_key values (11, 'abcde', 123, 'char', 3, 1, 23, 32, 332, 1.4, 25, '2017-11-11', '11:11:11', '2017-11-11 11:11:11', 1, 2017)' failed: 1292: Incorrect datetime value: '1' for column 'timestamp_test' at row 1

The result from queries just before the failure was:
use test;
CREATE TABLE `select_base_with_primary_key` (
`pk` bigint(11) NOT NULL AUTO_INCREMENT,
`varchar_test` varchar(255) DEFAULT NULL,
`integer_test` int(11) DEFAULT NULL,
`char_test` char(255) DEFAULT NULL,
`tinyint_test` tinyint(4) DEFAULT NULL,
`tinyint_1bit_test` tinyint(1) DEFAULT NULL,
`smallint_test` smallint(6) DEFAULT NULL,
`mediumint_test` mediumint(9) DEFAULT NULL,
`bigint_test` bigint(20) DEFAULT NULL,
`double_test` double DEFAULT NULL,
`decimal_test` decimal(10,0) DEFAULT NULL,
`date_test` date DEFAULT NULL,
`time_test` time DEFAULT NULL,
`datetime_test` datetime DEFAULT NULL,
`timestamp_test` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`year_test` year(4) DEFAULT NULL,
PRIMARY KEY (`pk`)
) ENGINE=STONEDB DEFAULT CHARSET=gbk;
safe_process[13111]: Child process: 13112, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue415/issue415.log'

Test stonedb.issue415 has failed 2 times, no more retries!

[ 36%] stonedb.issue417                         [ fail ]
        Test ended at 2022-07-13 13:12:40

CURRENT_TEST: stonedb.issue417
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/issue417.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/issue417.reject	2022-07-13 08:12:40.703000000 +0300
@@ -3,6 +3,4 @@
 insert into ttime values ('12:15:03'), ('18:30:20');
 select (val between '12:00:00' and '12:30:00') as agval from ttime;
 agval
-1
-0
 drop table ttime;

mysqltest: Result length mismatch

safe_process[13346]: Child process: 13347, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue417/issue417.log'

Retrying test stonedb.issue417, attempt(2/3)...

[ 36%] stonedb.issue417                         [ retry-fail ]
        Test ended at 2022-07-13 13:12:44

CURRENT_TEST: stonedb.issue417
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/issue417.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/issue417.reject	2022-07-13 08:12:44.165000000 +0300
@@ -3,6 +3,4 @@
 insert into ttime values ('12:15:03'), ('18:30:20');
 select (val between '12:00:00' and '12:30:00') as agval from ttime;
 agval
-1
-0
 drop table ttime;

mysqltest: Result length mismatch

safe_process[13580]: Child process: 13581, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue417/issue417.log'

Test stonedb.issue417 has failed 2 times, no more retries!

[ 40%] stonedb.issue429                         [ fail ]
        Test ended at 2022-07-13 13:12:47

CURRENT_TEST: stonedb.issue429
--- /data/stonedb57/install/mysql-test/suite/stonedb/r/issue429.result	2022-07-13 08:04:07.000000000 +0300
+++ /data/stonedb57/install/mysql-test/var/log/issue429.reject	2022-07-13 08:12:47.419000000 +0300
@@ -3,9 +3,6 @@
 insert into tt values ('06:34:12'), ('13:23:33');
 select * from tt where DATE(TIMESTAMP(val)) = CURDATE();
 val
-06:34:12
-13:23:33
 select * from tt where DATE(TIMESTAMP(val, val)) = CURDATE();
 val
-06:34:12
 drop table tt;

mysqltest: Result length mismatch

safe_process[13832]: Child process: 13833, exit: 1

 - the logfile can be found in '/data/stonedb57/install/mysql-test/var/log/stonedb.issue429/issue429.log'
The servers were restarted 12 times
Spent 0.192 of 93 seconds executing testcases

Check of testcase failed for: stonedb.casewhen stonedb.drop_column

Too many failed: Failed 10/12 tests, 16.67% were successful.

Failing test(s): stonedb.issue415 stonedb.add_column stonedb.issue417 stonedb.issue429 stonedb.issue405 stonedb.concat stonedb.issue410 stonedb.group_concat2 stonedb.group_concat stonedb.insert

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

Too many tests(10) failed! Terminating...
mysql-test-run: *** ERROR: Test suite aborted
`

### Expected behavior

run mtr tests success

### Environment

stonedb5.7
rocskdb6.12.6
centos7.9

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by hustjieke** [comment]
Now mtr in 5.7 is not work, would you make a pr to fix this?

**Comment by adofsauron** [comment]
> Now mtr in 5.7 is not work, would you make a pr to fix this?

sure

**Comment by adofsauron** [comment]
It does not continue to appear in later versions

**Comment by shangyanwen** [comment]
Not reoccurring, closed (from: Adofsauron)
