### ISSUE TITLE
bug: The storage engine of the conversion table causes the instance to crash

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#269]
### Describe the problem
```sql
mysql> show create table t_user_innodb\G
*************************** 1. row ***************************
       Table: t_user_innodb
Create Table: CREATE TABLE `t_user_innodb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(10) NOT NULL,
  `last_name` varchar(10) NOT NULL,
  `sex` varchar(5) NOT NULL,
  `score` int(11) NOT NULL,
  `copy_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_lastname` (`last_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10000001 DEFAULT CHARSET=utf8mb4
1 row in set (0.01 sec)

mysql> alter table t_user_innodb engine=stonedb;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> 2022-07-21T02:15:09.839722Z mysqld_safe Number of processes running now: 0
2022-07-21T02:15:09.845639Z mysqld_safe mysqld restarted


When the table is small, such as thousands of rows, the conversion can be successful; when the table is large, such as 10 million rows, the conversion process database instance crash 。
```

### Environment

root@htap1:~# uname -a
Linux htap1 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@htap1:~# /stonedb/install/bin/mysqld --version
/stonedb/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow: 
	Repository address: https://codeup.aliyun.com/6193102a4d2b371c479a9119/AtomStore/atomstore_for_mysql_5.7.git
	Branch name: stonedb5.7_0.1
	Last commit ID: d19b343
	Last commit time:  Mon May 16 23:36:52 2022 +0800
	Build time: 2022-05-17_11-35-23

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by DandreChen** [comment]
have fixed it
