### ISSUE TITLE
bug: INSERT INTO t1 SELECT * FROM t2 WHERE x IS NULL; condition is null, the StonedB engine reported an error

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#286]
### Describe the problem

```
CREATE TABLE t1 (
  ID_with_null int NULL,
  ID_better int NOT NULL,
  INDEX idx1 (ID_with_null),
  INDEX idx2 (ID_better)
)engine=stonedb;
INSERT INTO t2 VALUES (1,1), (2,1), (null,3), (null,3), (null,3), (null,3);

INSERT INTO t1 SELECT * FROM t2 WHERE ID_with_null IS NULL;
##The error results are as follows
ERROR 1030 (HY000): Got error 124 from storage engine
```

### Expected behavior

```
##Insert the success
INSERT INTO t1 SELECT * FROM t2 WHERE ID_with_null IS NULL;

##note：
1、The problem is that the where condition is null, so we need to analyze NULL；
2、The test was successful on InnoDB
```

### How To Reproduce

CREATE TABLE t1 (
  ID_with_null int NULL,
  ID_better int NOT NULL,
  INDEX idx1 (ID_with_null),
  INDEX idx2 (ID_better)
)engine=stonedb;
INSERT INTO t2 VALUES (1,1), (2,1), (null,3), (null,3), (null,3), (null,3);

INSERT INTO t1 SELECT * FROM t2 WHERE ID_with_null IS NULL;

### Environment

1. StoneDB for mysql5.7 (release)
2. Ubuntu 20.04.4

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by isredstar** [comment]
@shangyanwen Tianmu engine doesn‘t support the second index，so that executing `INSERT INTO t1 SELECT * FROM t2 WHERE ID_with_null IS NULL;`   statement reported the error.

**Comment by isredstar** [comment]
![image](https://user-images.githubusercontent.com/63028664/186168251-a43c98dc-32f8-4cb1-8d42-ad5a2170ce50.png)

**Comment by shangyanwen** [comment]
This bug is closed until later implementation based on requirements
