### ISSUE TITLE
feature: Use c++11/14/17 to make the code more concise and efficient

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#30]
**Is your feature request related to a problem? Please describe.**

>*Functions implement refactoring, and some functions are rewritten with new features, or refactored.*

**Describe the solution you'd like**

>*Use c++11/14/17 to make the code more concise and efficient.*

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
This work has already done, close it now.
