### ISSUE TITLE
建议：文档里不应该只是告诉我们“说明缺少文件，需要安装对应的依赖包。”

### ISSUE THREAD

**Issue by Shlpeng** [stoneatom/stonedb#304]
或许可以告诉我们比如参考如下链接找下所需依赖包：
https://pkgs.org/search/?q=libzstd.so.1

一、在我执行“ldd mysqld”命令检查的时候，提示缺少
1.1. libsnappy.so.1 => not found，
因我是amazon linux2系统，所以需要安装的是snappy：sudo  yum install snappy

1.2. libzstd.so.1 => not found
需要安装的是libzstd：sudo yum install libzstd

二、在我执行“ldd mysql”
2.1. libncurses.so.5 => not found
需要安装的是ncurses-compat-libs：sudo yum install ncurses-compat-libs

**Comment by Shlpeng** [comment]
同样其实不仅仅在stonedb56/install/stonedb.cnf下修改stonedb的根路径，我们有没有考虑把它提取出来当环境变量，省的到处都要修改

**Comment by RingsC** [comment]
Thanks for your comments.All your mentioned will be improved in future, or You can open a PR to help us to improve stonedb together.

**Comment by RingsC** [comment]
this issue has been fixed by @Shlpeng at #316 , So we close it.
