### ISSUE TITLE
question: Can this mydumper tool restore the backed up MySQL data to stonedb?

### ISSUE THREAD

**Issue by bluewaystar** [stoneatom/stonedb#306]
Can this mydumper tool restore the backed up MySQL data to stonedb?

If yes, the original database table engine in MySQL is engine=innodb. How to restore the table engine in stonedb to engine=stonedb after backup? Need to change manually one by one?

**Comment by zsp108** [comment]
> Can this mydumper tool restore the backed up MySQL data to stonedb?
> 
> If yes, the original database table engine in MySQL is engine=innodb. How to restore the table engine in stonedb to engine=stonedb after backup? Need to change manually one by one?

Yes,If you have a lot of tables, consider using shell scripts to modify them

**Comment by Nliver** [comment]
@bluewaystar Hello, i don't know whether our reply has solved your problem, but since you haven't replied for a long time, we will close this issue first. If you have any questions, please feel free to open it ~
