### ISSUE TITLE
feature: Try not to use plain type for data type, and it is better to use typedef for description

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#31]
**Is your feature request related to a problem? Please describe.**

>*Try not to use plain type for data type, and it is better to use typedef for description. 
The advantage is that if you change the type later, you don't need too much work. For the new version of c++, 
you can use using new_ type_ t = pain_ old_ data_ type.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
THIS is a part of #11, pls, refer to it for more information. And, now, here we close it, and feel free to reopen it again.
