### ISSUE TITLE
question: StoneDB does not support transactions, but "Show Engines" returns support for transactions. 

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#326]
mysql> show engines;
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                        | Transactions | XA   | Savepoints |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| CSV                | YES     | CSV storage engine                                             | NO           | NO   | NO         |
| MRG_MYISAM         | YES     | Collection of identical MyISAM tables                          | NO           | NO   | NO         |
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                             | NO           | NO   | NO         |
| BLACKHOLE          | YES     | /dev/null storage engine (anything you write to it disappears) | NO           | NO   | NO         |
| MyISAM             | YES     | MyISAM storage engine                                          | NO           | NO   | NO         |
| InnoDB             | DEFAULT | Supports transactions, row-level locking, and foreign keys     | YES          | YES  | YES        |
| ARCHIVE            | YES     | Archive storage engine                                         | NO           | NO   | NO         |
| STONEDB            | YES     | StoneDB storage engine                                         | YES          | NO   | NO         |
| FEDERATED          | NO      | Federated MySQL storage engine                                 | NULL         | NULL | NULL       |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables      | NO           | NO   | NO         |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
10 rows in set (0.00 sec)

**Comment by spidersq** [comment]
StoneDB does not support transactions。Why they say it is HTAP?

**Comment by hustjieke** [comment]
For TP we send to mysql plugin engine innodb,
For AP we send to our new mysql plugin engine stonedb column engine, both innodb and stonedb column engine use mysql sql layer

> StoneDB does not support transactions。Why they say it is HTAP?

**Comment by haitaoguan** [comment]
i wiil close this issue
