### ISSUE TITLE
feature: Whether class member functions begin with uppercase (subsequent unification)

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#33]
**Is your feature request related to a problem? Please describe.**

>*Whether class member functions begin with uppercase (subsequent unification).*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
This is a part of #11, which is called, `clean code prj`. Therefore, we do not trace in different issues, just only in one issue #11.
