### ISSUE TITLE
bug: The return result of replace into syntax is wrong

### ISSUE THREAD

**Issue by 422351990** [stoneatom/stonedb#34]
Describe the problem

mysql> REPLACE INTO study VALUES(12 , 'ij' , 112);
Query OK, 1 row affected (0.00 sec)
![image](https://user-images.githubusercontent.com/45621146/174469725-2eb8c7dd-f941-4597-90c9-3c56e3cdb341.png)

Expected behavior

Prompt you do not support this syntax for the time being

How To Reproduce

CREATE TABLE study(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
NAME VARCHAR(20) NOT NULL,
AGE INT(10)
)ENGINE=STONEDB;
INSERT INTO study VALUES(12 , 'a' , 10);
REPLACE INTO study VALUES(12 , 'ij' , 112);

Environment

Ubuntu 20.04.4 LTS
Server version: 5.6.24-StoneDB

Additional context

**Comment by haitaoguan** [comment]
StoneDB nonsupport replace into.
@hustjieke
