### ISSUE TITLE
website(stonedb): StoneDB open source community plus search capabilities.

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#350]
**Is your feature request related to a problem? Please describe.**

```
The Stonedb open source site has no search, and finding articles is a hassle
```
**Describe the solution you'd like**

```
There is a search box for finding articles quickly 
```

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
The architecture of website of stonedb is based on static pages, therefore, fulltext search will be supported after refactoring the the arch of stonedb website.

**Comment by Nliver** [comment]
![image](https://user-images.githubusercontent.com/34496563/201818355-c4501ebd-0506-41fb-853a-565febc39f28.png)

At present, the document website already supports the search function, welcome to experience ~

https://stonedb.io/

By the way, please note that only English documents can be searched on the English page（https://stonedb.io/）. If you want to search Chinese documents, you can switch the language first（https://stonedb.io/zh/）

**Comment by Nliver** [comment]
This ISSUE has been solved, I will close it
