### ISSUE TITLE
bug: Revised some code

### ISSUE THREAD

**Issue by xuejiao-joy** [stoneatom/stonedb#356]
### Describe the problem

Some code snippets in the following topics are outdated:

- compile-using-centos7
- compile-using-redhat7
- compile-using-ubuntu20.04

### Expected behavior

Update those code snippets.

### How To Reproduce

N/A

### Environment

N/A

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by RingsC** [comment]
see the comment in PR #358 ,now close it.
