### ISSUE TITLE
bug: alter table cause engine crash

### ISSUE THREAD

**Issue by DandreChen** [stoneatom/stonedb#366]
### Describe the problem

When the data volume of the table is large, such as table t_test has 19m, 2million data. When the table storage engine stonedb is changed to InnoDB, the database instance is normal. However, after the table storage engine InnoDB is changed back to tianmu, the database instance immediately crashes. The amount of data in the table is small or empty, and there is no such fault phenomenon.

#When the storage engine atomstore of the table is changed to InnoDB, the database instance is normal

alter table t_ test engine=InnoDB;

#When InnoDB, the storage engine of the table, is changed back to tianmu, the database instance will crash immediately

alter table t_ test engine=tianmu;

#Reorganize the table, that is, keep the storage engine of the table unchanged, execute the following two commands, and the database instance is normal

alter table t_ test engine=InnoDB;

alter table t_ test engine=tianmu;

According to the prompt, there may be a memory leak, but the problem remains when the private memory is reduced, such as changing the key buffer from 512M to 8m

### Expected behavior

alter table success

### How To Reproduce

1）
CREATE TABLE t_test(
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(10) NOT NULL,
  last_name VARCHAR(10) NOT NULL,
  sex VARCHAR(5) NOT NULL,
  score INT NOT NULL,
  copy_id INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU;

2）
DELIMITER //
    create PROCEDURE add_user(in num INT)
    BEGIN
        DECLARE rowid INT DEFAULT 0;
        DECLARE firstname CHAR(1);
        DECLARE name1 CHAR(1);
        DECLARE name2 CHAR(1);
        DECLARE lastname VARCHAR(3) DEFAULT '';
        DECLARE sex CHAR(1);
        DECLARE score CHAR(2);
        WHILE rowid < num DO
        SET firstname = SUBSTRING('赵钱孙李周吴郑王林杨柳刘孙陈江阮侯邹高彭徐',FLOOR(1+21*RAND()),1); 
        SET name1 = SUBSTRING('一二三四五六七八九十甲乙丙丁静景京晶名明铭敏闵民军君俊骏天田甜兲恬益依成城诚立莉力黎励',ROUND(1+43*RAND()),1); 
        SET name2 = SUBSTRING('一二三四五六七八九十甲乙丙丁静景京晶名明铭敏闵民军君俊骏天田甜兲恬益依成城诚立莉力黎励',ROUND(1+43*RAND()),1); 
        SET sex=FLOOR(0 + (RAND() * 2));
        SET score= FLOOR(40 + (RAND() *60));
        SET rowid = rowid + 1;
        IF ROUND(RAND())=0 THEN 
        SET lastname =name1;
        END IF;
        IF ROUND(RAND())=1 THEN
        SET lastname = CONCAT(name1,name2);
        END IF;
        insert INTO t_test (first_name,last_name,sex,score,copy_id) VALUES (firstname,lastname,sex,score,rowid);  
        END WHILE;
    END //
DELIMITER ;

3）
call add_user(2000000);

4）
alter table t_test engine=InnoDB;

5）
alter table t_test engine=tianmu;

### Environment

centos 7.9

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by RingsC** [comment]
@DandreChen pls, fix it ASAP.

**Comment by DandreChen** [comment]
ACK

**Comment by DandreChen** [comment]
same as https://github.com/stoneatom/stonedb/issues/269

**Comment by DandreChen** [comment]
Now the code is new and the logic is different. The problem is that this operation will consume a lot of disk space

**Comment by DandreChen** [comment]
Now the logic is to insert data directly
the code is
```
int RCTable::Insert(TABLE *table)
```

**Comment by DandreChen** [comment]
like ```INSERT INTO table2 SELECT * FROM table1;```
have same problem

**Comment by DandreChen** [comment]
now, has two ways to solve it
1. fix tempory table to use memory table or insert buffer
2. fix the  probelm of  consuming a lot of disk space

**Comment by DandreChen** [comment]
create table compare
normal table:
```
create table：
Proto_field (base):
Proto_field
ptr:
0x7ffc84024074 ""
table:
0x7fffec936d20
orig_table:
0x7fffec936d20
table_name:
0x7fffec936e10
field_name:
0x7ffc84011834 "first_name"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
40
flags:
4097
field_index:
1
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
CHECK_FIELD_IGNORE
m_warnings_pushed:
0



Proto_field (base):
Proto_field
ptr:
0x7ffc8402409d ""
table:
0x7fffec936d20
orig_table:
0x7fffec936d20
table_name:
0x7fffec936e10
field_name:
0x7ffc8401183f "last_name"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
40
flags:
4097
field_index:
2
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
CHECK_FIELD_IGNORE
m_warnings_pushed:
0




Proto_field (base):
Proto_field
ptr:
0x7ffc840240c6 ""
table:
0x7fffec936d20
orig_table:
0x7fffec936d20
table_name:
0x7fffec936e10
field_name:
0x7ffc84011849 "sex"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
20
flags:
4097
field_index:
3
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
CHECK_FIELD_IGNORE
m_warnings_pushed:
0

```

temporary table:
```
ptr:
0x7ffc84140ca4 "\374\177"
table:
0x7fffec936270
orig_table:
0x7fffec936270
table_name:
0x7fffec936360
field_name:
0x7ffc84a29144 "first_name"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
40
flags:
4097
field_index:
1
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
(unknown: 0x7ffc)
m_warnings_pushed:
0


ptr:
0x7ffc84140ccd ""
table:
0x7fffec936270
orig_table:
0x7fffec936270
table_name:
0x7fffec936360
field_name:
0x7ffc84a2914f "last_name"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
40
flags:
4097
field_index:
2
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
CHECK_FIELD_IGNORE
m_warnings_pushed:
0





Proto_field (base):
Proto_field
ptr:
0x7ffc84140cf6 ""
table:
0x7fffec936270
orig_table:
0x7fffec936270
table_name:
0x7fffec936360
field_name:
0x7ffc84a29159 "sex"
comment
key_start
part_of_key
part_of_sortkey
part_of_key_not_extended
unireg_check:
Field::NONE
field_length:
20
flags:
4097
field_index:
3
null_bit:
0 '\000'
is_created_from_null_item:
false
m_indexed:
false
gcol_info:
0x0
stored_in_db:
true
m_null_ptr:
0x0
m_is_tmp_nullable:
false
m_is_tmp_null:
false
m_count_cuted_fields_saved:
(unknown: 0x7ffc)
m_warnings_pushed:
0

```

**Comment by wisehead** [comment]
will fix it in next release.
