### ISSUE TITLE
feature: rocksdb needs to be added rocksdb.cmake file for processing

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#37]
**Is your feature request related to a problem? Please describe.**

>*At present, rocksdb adopts the same output method as boost, and rocksdb needs to be added rocksdb.cmake file for processing.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Pls, refer to #377 , and close it, and feel free to reopen it again.
