### ISSUE TITLE
question: Where can I download the.tar.gz file of version 5.7 directly?

### ISSUE THREAD

**Issue by bluewaystar** [stoneatom/stonedb#370]
hi,Where can I download the.tar.gz file of version 5.7 directly?

**Comment by haitaoguan** [comment]
The StoneDB 5.7 install package is not compiled. You need to manually compile it.You can read the official documents.
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-centos7
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-redhat7
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu20.04
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-docker

**Comment by haitaoguan** [comment]
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-centos7
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-redhat7
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu20.04
https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-docker

**Comment by haitaoguan** [comment]
The StonedB 5.7 v1.0.0 will be released on August 31, You will can download the tar.gz package.
https://stonedb.io/docs/download

**Comment by RingsC** [comment]
We will close this, and feel free to reopen it again. Thanks.
