### ISSUE TITLE
question: Gravity's online data transformation consulting

### ISSUE THREAD

**Issue by bluewaystar** [stoneatom/stonedb#371]
The gravity tool supports data filtering transformation, re command column transformation and delete column transformation when synchronizing. What I want to ask is whether it also supports the deletion and update of data in the master database (MySQL), and the deletion and update of data in the slave database (stonedb)?

**Comment by zsp108** [comment]
stonedb does not support delete operation for the time being, delete operation will be added in subsequent versions.
 See: https://stonedb.io/docs/about-stonedb/limits/
 Therefore, it is currently supported to use gravity to synchronize operations that are not restricted by StoneDB, such as MySQL update and insert, to StoneDB.

**Comment by Nliver** [comment]
Hello, our StoneDB-1.0.1 has supported the Delete function. You can try it~

https://github.com/stoneatom/stonedb/releases/tag/5.7-v1.0.1-GA

Due to the long time no reply, this issue will be closed
