### ISSUE TITLE
feature: Add code fault injection, synchronization point, etc.

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#38]
**Is your feature request related to a problem? Please describe.**

>*In order to improve the robustness of the system, it is necessary to add code fault injection, synchronization point, etc.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Same as #470 , but more details of how to add injection tests described in that issue. Therefore, we close this one, and keep that one.
