### ISSUE TITLE
feature: Integer type Usage

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#40]
**Is your feature request related to a problem? Please describe.**

>*When using an integer data type, its length and type must be specified to prevent different length implementations on different platforms*

**Describe the solution you'd like**

>*For example:

        uint8_t
        int8_t 

>make it portable. 

### Usage scenario:
    On-disk data
    Over the data wire
    Hardware registers
    Binary interface specifications
    Binary data structures

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Pls, refer to #11. Now, close it, and please feel free to reopen it again.
