### ISSUE TITLE
question: How independent is Tianmu engine? 

### ISSUE THREAD

**Issue by mzygQAQ** [stoneatom/stonedb#403]
## General Question

May I ask if it is possible to independently study the implementation of Tianmu engine without being familiar with MySQL source code?

**Comment by RingsC** [comment]
Yes, definitely, Tianmu is known as column-based engine. All codes are used to implemented a columnar-based engine, includes: `handler`, `core`, `indexes`, modules, etc.  
We recommand your to read some papers on column-based database engine, and we are welcome to hear your voice via any ways, mails, issues, etc. 
At last, we will lauch our code explanation or code study in future.

**Comment by RingsC** [comment]
By the way, a little bit of mysql source knowledge is better for your understanding Tianmu engine, especially, in `handler` modules.

**Comment by haitaoguan** [comment]
Yes,you can.Because StoneDB is fully compatible with the MySQL. Good luck.

**Comment by mzygQAQ** [comment]
> Yes,you can.Because StoneDB is fully compatible with the MySQL. Good luck.

thanks :)

**Comment by mzygQAQ** [comment]
> By the way, a little bit of mysql source knowledge is better for your understanding Tianmu engine, especially, in `handler` modules.

thanks for you reply :)  
The handler module you mentioned should be the abstract layer interface of MySQL underlying docking with different storage engines.  If I don't understand it correctly, I should only read it from  [TianmuHandler](https://github.com/stoneatom/stonedb/blob/stonedb-5.7/storage/tianmu/handler/tianmu_handler.h#L28) ?
