### ISSUE TITLE
feature: alter table need to support  alter column length and column type

### ISSUE THREAD

**Issue by DandreChen** [stoneatom/stonedb#411]
**Is your feature request related to a problem? Please describe.**

i can not alter colum length and colun type
return ”ERROR 2233 (HY000): Be disgraceful to storage engine, operating is forbidden!“

**Describe the solution you'd like**

 need to support  alter column length and column type

**Describe alternatives you've considered**

use copy algorithm to support it

**Additional context**

**Comment by DandreChen** [comment]
Through investigation, find that alter table supports two algorithms: copy algorithm and inplace algorithm, need to investigate them

**Comment by DandreChen** [comment]
through debugging code, when i use "alter table  'ablename' modify  'columname  type change' " , the code always return HA_ALTER_ERROR:

> enum_alter_inplace_result inplace_supported=table->file->check_if_supported_inplace_alter(altered_table                                                &ha_alter_info);


because next code do not support this action:

> enum_alter_inplace_result TianmuHandler::check_if_supported_inplace_alter([[maybe_unused]] TABLE *altered_table,
>                                                                            Alter_inplace_info *ha_alter_info)
>  {
>   if ((ha_alter_info->handler_flags & ~TIANMU_SUPPORTED_ALTER_ADD_DROP_ORDER) &&
>        (ha_alter_info->handler_flags != TIANMU_SUPPORTED_ALTER_COLUMN_NAME)) {
>        return HA_ALTER_ERROR;
>   }
>   return HA_ALTER_INPLACE_EXCLUSIVE_LOCK;
> };

**Comment by DandreChen** [comment]
find the function of th innodb engine , always  return HA_ALTER_INPLACE_NOT_SUPPORTED

>  for (uint i = 0; i < ha_alter_info->index_drop_count; i++) {
>  	if (!my_strcasecmp(system_charset_info, ha_alter_info->index_drop_buffer[i]->name, FTS_DOC_ID_INDEX_NAME))
>       {
>  		ha_alter_info->unsupported_reason = 
> innobase_get_err_msg(ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS);
>  		DBUG_RETURN(HA_ALTER_INPLACE_NOT_SUPPORTED);
>  	}
>  }
>

**Comment by DandreChen** [comment]
so ,we can use this method

**Comment by cjkbjhb** [comment]
The code section above is not read friendly.

**Comment by DandreChen** [comment]
have made it better
