### ISSUE TITLE
Feature: Support MySQL 8.0 

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#419]
**Is your feature request related to a problem? Please describe.**

Now StoneDB has already support with mysql 5.6 and 5.7, it's time to do support on `MySQL 8.0`.
This will be a huge job.

Recently Task List:
- #695
- #697 
- #698 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyli029** [comment]
Base Line Version: `MySQL 8.0.30`

**Comment by andyli029** [comment]
milestone： https://github.com/stoneatom/stonedb/milestone/4

**Comment by hustjieke** [comment]
Recently Task List:
- #695
- #697 
- #698 
- #699

**Comment by hustjieke** [comment]
Subtasks next will be done in stonedb-8.0-v1.0.1
https://github.com/stoneatom/stonedb/issues/699
https://github.com/stoneatom/stonedb/issues/700

Close issue now!
