### ISSUE TITLE
docs: 既然是国产的，中文文档在哪里 ，官网地址是什么

### ISSUE THREAD

**Issue by BenTaotao** [stoneatom/stonedb#420]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7/CONTRIBUTING.md).

### Description

既然是国产的，中文文档在哪里 ，官网地址是什么

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Nliver** [comment]
Our Chinese document is here：https://stonedb.io/zh/

**Comment by RingsC** [comment]
Close it, feel free to reopen it again.
