### ISSUE TITLE
bug: High availability master-slave delay StoneDB reported an error

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#426]
### Describe the problem

```
1、Mysql InnoDB is the main, StonedB is the slave node
2、Use the INSERT of the sysbench script to insert 10 tables with 80,000 rows each into the host
3、Set the parameters：tianmu_insert_delayed=off
4、When the data was synchronized to 5073 seconds later, StonEDB reported an error, as shown in the following figure


```
![image](https://user-images.githubusercontent.com/107781103/185726663-48d05599-6f02-442b-a44b-a5b200cc2075.png)
![image](https://user-images.githubusercontent.com/107781103/185726673-56729ad6-f847-4020-92eb-0290e8ba1441.png)
### Expected behavior

Innodb synchronised data to StonEDB with low latency, and data can be synchronized

### How To Reproduce

```
1、Mysql InnoDB is the main, StonedB is the slave node
2、Use the INSERT of the sysbench script to insert 10 tables with 80,000 rows each into the host
3、Set the parameters：tianmu_insert_delayed=off
4、Perform the tests to observe the results
```

### Environment

```
1、5.7.36-StoneDB
        Last commit ID: 05eb397
        Last commit time: Date:   Mon Aug 15 14:05:47 2022 +0800
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by lylth** [comment]
Test package problem, the problem is solved after updating the test package
