### ISSUE TITLE
[RFC] Loading Data

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#428]
Hi~there, StoneDB v2.0 design is coming, we are now doing work on `Loading Data`, just like MySQL heatwave!
We'll Discuss questions like:

- How to load full data.
- Parallel scan
- Format from `row` to `column`
- Incremental loading

Ref from: 
https://www.oracle.com/mysql/heatwave/#rc30p1
<img width="998" alt="image" src="https://user-images.githubusercontent.com/18331104/185852045-45a6c61d-5600-4806-95cd-7d57c568ae4b.png">

**Comment by RingsC** [comment]
This will be given in #424 , we dont talk about the loading mechanism in seperate issue. And we do not think it's a independent issue in whole design work.
