### ISSUE TITLE
feature: clang-tidy

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#43]
**Is your feature request related to a problem? Please describe.**

>*clang-tidy*

**Describe the solution you'd like**

>clang-tidy GitHub URL:
https://github.com/google/leveldb/commit/297e66afc1dda3f3d7a7cc2022030164c302cb7a

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Now, we are using `clang-format` to check the codes. And, close it when need reopen it again.
