### ISSUE TITLE
Supprot DELETE Statement

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#451]
## Current status

|Database types that support column storage|Whether delete is supported|remarks|
|---|---|---|
|MariaDB ColumnStore|Yes||
|SQL Server|Yes||
|Oracle In-Memory Column Store|Yes||
|MySQL HeatWave|No|It is mainly used as an auxiliary engine and supports DML synchronization|
|TiFlash|No|It is mainly used as an auxiliary engine and supports DML synchronization|
|PolarDBIn-Memory Column Index|Yes||
|openGauss|Yes||
|ClickHouse|Yes|Nonstandard delete operation|

## Summary of delete schemes for column storage
|Database types that support column storage|Underlying storage structure|Delete policy|
|---|---|---|
|MariaDB ColumnStore|Fixed size data block + Metadata|Mark delete|
|SQL Server|Column storage index + row group + column segment|Mark delete|
|PolarDB In-Memory Column Index|Column storage index + RowGroup+DataPack+ metadata|Mark delete|
|openGauss|DataPack + Metadata|Mark delete|
|ClickHouse|Orderly storage + partitioned packets|New partition replace|

## Implementation flowchart of delete function of Tianmu engine

<img width="330" alt="image" src="https://user-images.githubusercontent.com/106147765/187364293-bdee86c8-e6ca-4f98-8b03-62376ed4d96e.png">

---
## Support (Single-Table Syntax) DELETE FROM tb_name
>At present, we support the truncate function. The delete all function of a single table directly reuses the truncate logic

## Conditional delete function
>Conditional delete here we use the strategy of marked deletion.
The storage structure of the columnar database determines that the data of the entire table must be moved and reorganized when the real data is deleted. In addition to deleting useless rows, it also needs to merge data blocks. In the case of a large amount of data, deleting real data will be a very large action, which will not only consume a large amount of IO resources and CPU resources of the machine, but also the deletion speed is not high. This is also the reason why the current mainstream manufacturers that support column databases use mark deletion.
### 1. Inside the pack

Disadvantages: each deletion requires reading and decompressing / compressing the package involved. (other schemes also need to read and decompress the pack when modifying metadata)

Advantages: the data can be left blank when the tag is deleted, which can effectively release the space of the string type. At the same time, it can optimize the data filtering scenarios of select, insert and update with where clauses. There is no need to modify the upper logic. The overall logic is simple. The modified surface is mainly concentrated in the pack layer.

### 2. Inside the DPN

Advantages: deleting does not need to read and save the package, only needs to modify the metadata, and the size of the delete bitmap is fixed

Disadvantages: the delete bitmap is too large, generally 8192 bytes, far exceeding the size of the original metadata, which will greatly affect the reading and writing efficiency of the original DPN.

### 3. Rcattr:: in HDR

Advantages: only one delete bitmap needs to be maintained in a column, saving storage space.

Disadvantages: because the number of data in the column will change at any time, unlike the number of data in a single package maintained by pack and DPN, which is fixed, the size of the delete bitmap also needs to change at any time.

### 4. Add a deletebitmap file for each column

Add the deletebitmap index in the DPN, which corresponds to the deletebitmap in the deletebitmap file, as shown in the following figure:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/106147765/187443405-95c79769-222b-4230-9aff-a94b750c3ea3.png">

Deletebitmap is managed by Tianmu:: Core:: columnshare. Currently, DPN is also managed by Tianmu:: Core:: columnshare.

Advantages: it can correspond to the DPN one-to-one, and the size of the delete bitmap is fixed.

Disadvantages: a new file needs to be added to maintain the delete bitmap. When reading the DPN file, you also need to read the delete bitmap file, which will add an IO.
### Our final strategy
We will use scheme 1 to store the delete bitmap in the pack to implement the mark deletion
## Mark delete the logic to be modified
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/106147765/187450301-3d1d446c-18f1-48b8-a063-f35ec8c48bad.png">

## Data filter logic optimized process

<img width="303" alt="image" src="https://user-images.githubusercontent.com/106147765/187451541-ac2b06aa-1b9d-465f-8c65-1aa912a481d0.png">

**Comment by RingsC** [comment]
One question: Do we run the merge operations, when the data in DP is less than half of original one.  Taking this for instance, There two DPs store contineously on disk, and after deleting operation,  the size of every deleted DPs is a half of original one. Do we run merge operations to compact these tow DPs into a new one?  If yes, when start this operation.

**Comment by konghaiya** [comment]
Good question!
This is one of the invalid space cleaning functions after deletion. 
We plan to implement this function in the near future.
- #455

**Comment by RingsC** [comment]
To be a formal design doc, and will be listed in `stonedb.io`.
