### ISSUE TITLE
feature: ASSERT，CHECK_CONDITION，In accordance STONEDB_ERROR with style

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#47]
**Is your feature request related to a problem? Please describe.**

>*ASSERT，CHECK_CONDITION，In accordance STONEDB_ERROR with style.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Refer to #11, now, we close it, and feel free to reopen it again.
