### ISSUE TITLE
bug: stonedb has two LZ4 versions

### ISSUE THREAD

**Issue by lujiashun** [stoneatom/stonedb#471]
### Describe the problem

1. in extra/lz4/lz4-1.9.3, there are two files lz4.cpp lz4.h.(obviously, the version is 1.9.3)
2. in stonedb\storage\tianmu\compress, there are two files lz4.cp lz4.h(from lz4.h,we can see that the version is 1.7.1)
3. two version’s lz4 is used，though the tianmu's lz4 using namespace Tianmu::compress, but some abnoraml behavier can be found.
3.1 firstly, the objcect file lz4.cpp.o( tianmu file) 's symbol(using nm command) ,function LZ4_uncompress is 
 _ZN6Tianmu8compress14LZ4_uncompressEPKcPci; while function LZ4_compress is LZ4_compress( no namespace name).
though, stonedb5.7 can be compiled pass，but maybe exists some risk.
3.2 in stondb8.0,in  ubuntu  the gcc report multiple definition described as below:(centos7.9 works well)
      https://github.com/andyli029/mysql-server-mysql-8.0.30/issues/102
3.3 in stondb8.0,delete the tianmu's  lz4.cpp lz4.h files, it works well, the build system can find the extra's lz4.
4. anyway,it is not necessary to use two different lz4 version, delete is and depend on the extra is a suitable option(tianmu's verison is older).

### Environment

version:StoneDB5.7/StoneDB8.0  
OS:UBUNTU20.04

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by RingsC** [comment]
The latest version of Lz4 is 1.9.4, and is a stable version. It's better to upgrade that to 1.9.4. 
https://github.com/lz4/lz4/releases/tag/v1.9.4
```
Release Notes:
Improved decompression speed
```

As the notes said, the decompression is speeded up, therefore, the latest version is recommended. I think that we should upgrade it to 1.9.4.
