### ISSUE TITLE
feature: Separation of interface and impl

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#48]
**Is your feature request related to a problem? Please describe.**

> *Separation of interface and impl.*

**Describe the solution you'd like**

>*The interface needs to be separated from the concrete implementation.*
*Interfaces are mainly declarations and definitions (in the form of pure virtual classes),*
*Impl is a concrete implementation.*

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
This also can be one of #11, because refactor the inferfaces of some classes can improve the code quality, and readability.
