### ISSUE TITLE
feature: Do not use #define or typedef, othewise use 'using'.

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#49]
**Is your feature request related to a problem? Please describe.**

> *Do not use #define or typedef, othewise use 'using'.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
This is a part of clean code, #11,  pls, refer to that issue for more information, close this issue, and anyone feel free to reopen it again. Thanks.
