### ISSUE TITLE
feature: Type casting, don't use c-like type-cast, just using c++ style, static_cast, dynamic_cast, ... etc.

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#50]
**Is your feature request related to a problem? Please describe.**

> *Type casting, don't use c-like type-cast, just using c++ style, static_cast, dynamic_cast, ... etc.*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
We are following the google coding style, and you can refer to #11 for more information. And, now, we close it, and anyone feel free to reopen it again.
