### ISSUE TITLE
bug:  incorrect result set.String not cast to int correctly

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#501]
### Describe the problem

```
CREATE TABLE t1 (c1 INT NOT NULL)engine=tianmu;
INSERT INTO t1 VALUES(4188.32999999999992724042385816574096679687500),
('4188.32999999999992724042385816574096679687500'), (4188);
SELECT * FROM t1;
#Incorrect test results
Empty set (0.00 sec)
```

### Expected behavior

```
# Correct test results（note:Innodb test verification, test results are as follows）
SELECT * FROM t1;
+------+
| c1   |
+------+
| 4188 |
| 4188 |
| 4188 |
+------+
```

### How To Reproduce

```
CREATE TABLE t1 (c1 INT NOT NULL)engine=tianmu;
INSERT INTO t1 VALUES(4188.32999999999992724042385816574096679687500),
('4188.32999999999992724042385816574096679687500'), (4188);
SELECT * FROM t1;
```

### Environment

[root@dev bin]# ./mysqld --version
./mysqld  Ver 5.7.36_v1.0.0_beta-StoneDB for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7
        Branch name: stonedb-5.7
        Last commit ID: eed32f6
        Last commit time: Date:   Wed Aug 3 11:19:48 2022 +0800
        Build time: Date: Wed Aug  3 13:01:31 CST 2022

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by taofengliu** [comment]
I can not reproduce this issue with the newest code of branch 'stonedb-5.7-dev' in Ubuntu20.04.
Like the screenshot shows bellow, I can get the right output.Please check this issue again. @shangyanwen 
![2022-09-21 21-29-43屏幕截图](https://user-images.githubusercontent.com/81315978/191516949-91e013b7-7b94-4a5c-9c28-fa034282dac9.png)

**Comment by hustjieke** [comment]
> I can not reproduce this issue with the newest code of branch 'stonedb-5.7-dev' in Ubuntu20.04. Like the screenshot shows bellow, I can get the right output.Please check this issue again. @shangyanwen ![2022-09-21 21-29-43屏幕截图](https://user-images.githubusercontent.com/81315978/191516949-91e013b7-7b94-4a5c-9c28-fa034282dac9.png)

Thanks for your infos.  @taofengliu 
Can you make a check  again ? @shangyanwen

**Comment by shangyanwen** [comment]
stonedb 5.7_v1.0.1,test pass
