### ISSUE TITLE
feature: A pointer variable must have an inital value

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#51]
**Is your feature request related to a problem? Please describe.**

> *pinter variable must have an inital value.*

**Describe the solution you'd like**

Bad: 

    char* p ;
Good:

    char p(nullptr); or  char *p =nullptr;

Or if any variables defined, it must be with default value.  For example:

    int width = 0; 
    char* p = nullptr;

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
This issue is a part of #11, pls refer to that issue for more information.  Therefore, we close it, and feel free to reopen it again.  we are following the google coding guide, If you can visit https://google.github.io/styleguide/cppguide.html for details.
