### ISSUE TITLE
feature: Upgrade tools for Tianmu engine.

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#510]
**Is your feature request related to a problem? Please describe.**

The Tianmu engine needs an upgrade tools, which provides some tools for upgrade Tianmu from an old version to a new version. The new version maybe changes the format of meta-data or format of data. These format change will lead the new version of StoneDB can read the old-format data. Therefore, StoneDB should provide an upgrading solution. 

All our information about Tianmu upgrading is in this directory.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
First of all, we add a new directory, 'upgrade' , in Tianmu engine.
