### ISSUE TITLE
feature: The naming of functions should be clear and easy to understand, conform to Chinese and foreign thinking habits, and avoid Chinese naming rules;

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#52]
**Is your feature request related to a problem? Please describe.**

The naming of functions should be clear and easy to understand, conform to Chinese and foreign thinking habits, and avoid Chinese naming rules;

**Describe the solution you'd like**

For example: NoNulls (), which returns the number of Null.
Suggestion: NumOfNulls();

"types::BString DoGetMaxString(const core::", the "doget" verb is repeated in such function names,
Just keep one. Suggestion: name with "GetMaxString".

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Same as issue #11  , Closed it.
