### ISSUE TITLE
bug: (mtr) There are unsupported items of the Tianmu engine in the test case

### ISSUE THREAD

**Issue by konghaiya** [stoneatom/stonedb#526]
### Describe the problem

![lQLPJxa0pustK7_NAv_NA82wc50-N2a3Yn8DKQvs6UCJAA_973_767](https://user-images.githubusercontent.com/106147765/191425187-cbaa4422-670e-402c-9a3f-1eeb73e70363.png)

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by RingsC** [comment]
Pls, Using Text to descibe the issue message.  @konghaiya

**Comment by konghaiya** [comment]
The problem has been solved in the previous submission. This issue can be closed.
Details can be found in:  
- #536
