### ISSUE TITLE
bug: MySQL server has gone away when call a procedure

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#529]
### Describe the problem

![image](https://user-images.githubusercontent.com/53512869/191448571-806ea8b7-bb96-499f-8416-3c048f3a130c.png)

### How To Reproduce

```sql
CREATE TABLE `one_data`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '名称',
  `sort_number` int(11) NULL DEFAULT NULL COMMENT '序号',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 472 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci COMMENT = '创建事件每秒添加一条数据' ROW_FORMAT = Dynamic;


delimiter //
create procedure doinsert()
begin
 declare i int;  
 set i = 0; 
while(i<=200) do
  INSERT INTO `one_data`( `name`, `sort_number`, `create_time`) VALUES (CONCAT('名称',i), i, NOW());
  set i = i+1; 
end while;  
end;//

delimiter ;

call doinsert();
```

### Environment

root@test1:/etc# cat os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

root@test1:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: git@github.com:lylth/stonedb-ee.git:stonedb-5.7
        Branch name: stonedb-5.7
        Last commit ID: 0291a62
        Last commit time: Date:   Thu Sep 15 19:50:46 2022 +0800
        Build time: Date: 2022年 09月 16日 星期五 22:02:41 CST

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by lylth** [comment]
It has been solved on the enterprise version, the community version does not have this bug
