### ISSUE TITLE
bug: With Navicat, the exported statement contains [USING LSMTREE]

### ISSUE THREAD

**Issue by 422351990** [stoneatom/stonedb#53]
escribe the problem:
With Navicat, the exported statement contains [USING LSMTREE]
The index type of InnoDB is BTREE, but the build statement with "USING BTREE" does not report an error.
The index type of StoneDB is LSMTREE, but the statement statement with "USING LSMTREE", it will raise an syntax error.

Expected behavior:
Export statements do not include [USING LSMTREE]

How To Reproduce:
**step1**、create table
CREATE TABLE `teacherS`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT  ,
  `NAMES` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ,
  `AGE` int(10) NULL DEFAULT NULL  ,
  PRIMARY KEY (`ID`) 
) ENGINE = STONEDB

**step2**、Export using Navicat

**step3**、View the SQL file
CREATE TABLE `teacher3`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Size[MB]: 0.1; Ratio: 0.00\0 ',
  `NAMES` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Size[MB]: 0.1; Ratio: 0.00\0 ',
  `AGE` int(10) NULL DEFAULT NULL COMMENT 'Size[MB]: 0.1; Ratio: 0.00\0 ',
  PRIMARY KEY (`ID`) USING LSMTREE
) ENGINE = STONEDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'Overall compression ratio: 0.000, Raw size=0 MB' ROW_FORMAT = Compressed;
SET FOREIGN_KEY_CHECKS = 1;
step4、import the SQL file
step5、import fail
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LSMTREE ) ENGINE = STONEDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMEN' at line 1

Environment:
win10 
Navicat
Server version: 5.6.24-StoneDB

**Comment by RingsC** [comment]
The LSMTREE is not  a type of index, and also is not an syntax supported.
