### ISSUE TITLE
feature: It is unnecessary to include too many <xxx.h> in ".h"file, and put these header files that need to be included into " .cpp "file

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#54]
**Is your feature request related to a problem? Please describe.**

> *It is unnecessary to include too many <xxx.h> in ".h" file, and put these header files that need to be included into " .cpp "file*

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Refer to #11 for more information. And, now we close it, and feel free to reopen this issue again.
