### ISSUE TITLE
feat(stonedb): Add build scripts to build StoneDB more convenient.

### ISSUE THREAD

**Issue by andyli029** [stoneatom/stonedb#544]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
For stonedb, `scripts` folder contains some scripts for building or startup an instance, etc. And, we recommand that the users to use command line to build or startup their instance mannually. The scripts are not recommaned.
