### ISSUE TITLE
feat(StoneDB): Porting `JOIN::join_optimize` to StoneDB 8.0

### ISSUE THREAD

**Issue by andyli029** [stoneatom/stonedb#545]
**Is your feature request related to a problem? Please describe.**

Porting the JOIN::optimize from StoneDB 5.7 to StoneDB 8.0.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
In mysql server commit: 5eef3b35da3ef2ada74dd53f6b04252523706b7f. It rename the `internal_remove_eq_conds` to `remove_eq_conds`. and removes original version of `remove_eq_conds`.

**Comment by RingsC** [comment]
change `execute_sqlcom_select`  to `execute_show`  @[this commit](https://github.com/mysql/mysql-server/commit/447c4cc3c4f#diff-63e8ebf88d9284969b752c9680d4f5aa488e9a4132bdeca169a547cb77302407) 

But in this [commit@4a7ae675095](https://github.com/mysql/mysql-server/commit/4a7ae675095), they remove `execute_show` from source code. `Sql_cmd_show` is used for showing command.
