### ISSUE TITLE
feature: Adjust the path of the generated file after compilation

### ISSUE THREAD

**Issue by konghaiya** [StoneAtom/stonedb#56]
**Is your feature request related to a problem? Please describe.**

> *At present, the installation directory will be deleted and MySQL will be stopped every time when compiling.*

**Describe the solution you'd like**

> *We need to adjust the path of the compilation generation file to avoid conflicts with the already installed StoneDB.*

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
What's '"No.41" ?  Be specific.
