### ISSUE TITLE
feature(Tianmu): Refactor the Tianmu storage engine. 

### ISSUE THREAD

**Issue by RingsC** [stoneatom/stonedb#560]
**Is your feature request related to a problem? Please describe.**

Due to the chaotic logic of Tianmu engine. Such as call-relationship, the non-clear relationship between `rcbase_hton`, `ha_rcengine_` and `ha_kvstore_`. 

Especially in `sql\sql_optimizer.cc`, `JOIN::optimize` introudces a variable `part` to describe the which part we are in. That's a ugly code. 

the fiiles are following: 
```
storage/tianmu/handler/tianmu_handler_com.cpp
sql\sql_parser.cc
```
**Describe the solution you'd like**

Making the clean code.  the relationships in Tiamu will be in a clean status, just as InnoDB does. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
Transfer to #698
