### ISSUE TITLE
question: ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by yongpan0709** [stoneatom/stonedb#631]
## General Question
- Searched open and closed [GitHub issues#228](https://github.com/stoneatom/stonedb/issues/228)
### Describe the problem
Comparing the following 2 screenshots, this error(1071) may be caused by encoding method utf8mb4.
![image](https://user-images.githubusercontent.com/84337599/193247252-ede0a849-7db3-4836-879d-e3124d6546f9.png)

![image](https://user-images.githubusercontent.com/84337599/193247399-e57354e9-904c-4887-977e-ecaf46dfa208.png)

### Environment

1. StoneDB for mysql5.7-dev
Based on branch: stonedb-5.7-dev，commit id: c2be08d9bb5716beb76f8695278acbdcaac06c75 
![image](https://user-images.githubusercontent.com/84337599/193247753-7fa89ba7-c472-4561-8bce-b60f1b63af6d.png)

![image](https://user-images.githubusercontent.com/84337599/193247644-9f1e5985-6da5-4eb2-935a-9b6ecb6474fd.png)

2. Ubuntu 20.04.4

**Comment by lujiashun** [comment]
1.  innodb has  a variable "innodb_large_prefix", its default values is true, it can store a 3072 bytes column belonged to  a primary key；if set  "innodb_large_prefix" false, its max bytes is 767.
2. tianmu has a variable  “tianmu_large_prefix”, its defualt value is false，it can store up to 767 bytes；if turn on the system variable， it can store up to 3072 bytes.
3. maybe we can set “tianmu_large_prefix” default value to ON as innodb does.
```
sql> show variables like "%large_prefix%";
+-----------------------------------+-------+
| Variable_name                     | Value |
+-----------------------------------+-------+
| innodb_large_prefix               | ON    |
| tianmu_large_prefix               | OFF   |
+-----------------------------------+-------+
2 rows in set (0.00 sec)

mysql> create table t1(a varchar(200) charset utf8mb4 not null, primary key(a)) engine=tianmu;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

mysql> set global tianmu_large_prefix=ON;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t1(a varchar(200) charset utf8mb4 not null, primary key(a)) engine=tianmu;
Query OK, 0 rows affected (0.04 sec)

mysql> set global innodb_large_prefix = off;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> create table t2(a varchar(200) charset utf8mb4 not null, primary key(a)) engine=innodb;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```
