### ISSUE TITLE
question: unknown variable 'stonedb_ini_allowmysqlquerypath=1' on MySQL 5.7-dev

### ISSUE THREAD

**Issue by yongpan0709** [stoneatom/stonedb#632]
## General Question
![image](https://user-images.githubusercontent.com/84337599/193487123-1dfe03bb-4306-4a7b-a415-c66d62cbea3a.png)

![image](https://user-images.githubusercontent.com/84337599/193486846-8668e5fa-fe2d-408c-9917-3d1d2e1c9ff4.png)

### Environment
StoneDB for mysql5.7-dev
Based on branch: stonedb-5.7-dev，commit id: https://github.com/stoneatom/stonedb/commit/c2be08d9bb5716beb76f8695278acbdcaac06c75
![image](https://user-images.githubusercontent.com/84337599/193487160-735414a0-499f-4948-8c15-43fa861cab53.png)
![image](https://user-images.githubusercontent.com/84337599/193487171-70ddd160-5eb5-4661-8072-08e23108c5c4.png)

Ubuntu 20.04.4

**Comment by lujiashun** [comment]
ACK

**Comment by lujiashun** [comment]
variable **stonedb_ini_allowmysqlquerypath** is changed to **tianmu_ini_allowmysqlquerypath** with storage engine is named from stonedb to tianmu ( https://github.com/stoneatom/stonedb/commit/eed32f66478d304cccd2886d713b4895500fde9c   ,Aug 3) ；

commit id https://github.com/stoneatom/stonedb/commit/c2be08d9bb5716beb76f8695278acbdcaac06c75  is commited in Sep 27；

ref：https://stonedb.io/docs/about-stonedb/limits/
ref：https://stonedb.io/zh/docs/about-stonedb/limits/
