### ISSUE TITLE
feature(Tianmu): in the initialize module, need to add log information

### ISSUE THREAD

**Issue by DandreChen** [stoneatom/stonedb#637]
**Is your feature request related to a problem? Please describe.**

If an error occurs in the initialization module, the log cannot be used to determine where the error is.
<img width="699" alt="lQLPJxa682pL3wDNAiXNBXawD9j2i0x1Be4DM13WrkDsAA_1398_549" src="https://user-images.githubusercontent.com/34465107/193962451-bf69b1d1-2579-42b5-9505-bbe5727e5b77.png">

**Describe the solution you'd like**

Add more logs in the initialization module, so that you can determine the error through the logs

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
No longer used, closed it now.
