### ISSUE TITLE
bug: fix the ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Nliver** [stoneatom/stonedb#641]
### Describe the problem
Fixed formatting errors caused by indentation

### Expected behavior
I'm going to fix it~

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by hustjieke** [comment]
https://github.com/Nliver/stonedb/blob/issue%23641/.github/ISSUE_TEMPLATE/bug_report.yml
