### ISSUE TITLE
bug: valgrind:definitely lost:21 bytes in 1 blocks

### ISSUE THREAD

**Issue by shangyanwen** [StoneAtom/stonedb#66]
**Describe the problem**

```
21 bytes in 1 blocks are definitely lost in loss record 5 of 316
at 0x484147B: calloc (vg_replace_malloc.c:1328)
by 0xBFECE9: my_malloc (my_malloc.c:38)
by 0xE1A368: add_pfs_instr_to_array(char const*, char const*) (pfs_server.cc:251)
by 0x897A8B: mysqld_get_one_option (mysqld.cc:8792)
by 0xC0FE1C: my_handle_options (my_getopt.cc:613)
by 0x89AA85: handle_early_options() (mysqld.cc:6881)
by 0x89FC72: mysqld_main(int, char**) (mysqld.cc:5272)
by 0x4B22082: (below main) (libc-start.c:308)
```

**Expected behavior**

no definitely lost
**How To Reproduce**

1、Create eight tables for TPCH
2、Generate 2G of test data
3、Import data into each of the eight tables（Import the way）

**Environment**

1、Ubuntu 20.04.4
2、valgrind-3.19.0

**Additional context**

See the attachment for creating tables 、 importing data、error log
[valgrind-stonedb.log](https://github.com/stoneatom/stonedb/files/8938430/valgrind-stonedb.log)
[create_table.txt](https://github.com/stoneatom/stonedb/files/8938433/create_table.txt)
[load_data.txt](https://github.com/stoneatom/stonedb/files/8938435/load_data.txt)

**Comment by konghaiya** [comment]
When using Valgrind for testing, it is best to use the program compiled in the debug mode.

**Comment by konghaiya** [comment]
The solution is the same as 
- #60
