### ISSUE TITLE
bug:valgrind:possibly lost: 24,542,118 bytes in 169 blocks

### ISSUE THREAD

**Issue by shangyanwen** [StoneAtom/stonedb#67]
**Describe the problem**

A total of 141 questions, please refer to the attachment：possibly_lost.txt
**Expected behavior**

no possibly lost
**How To Reproduce**

1、Create eight tables for TPCH
2、Generate 2G of test data
3、Import data into each of the eight tables（Import the way）

**Environment**

1、Ubuntu 20.04.4
2、valgrind-3.19.0

**Additional context**

[create_table.txt](https://github.com/stoneatom/stonedb/files/8938716/create_table.txt)
[load_data.txt](https://github.com/stoneatom/stonedb/files/8938717/load_data.txt)
[possibly_lost.txt](https://github.com/stoneatom/stonedb/files/8938720/possibly_lost.txt)

**Comment by konghaiya** [comment]
This problem is a MySQL problem and will not be solved for the time being
