### ISSUE TITLE
bug: DELETE and SELECT query should have the same logic.

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#682]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

when SELECT .. where is NULL, it returns an empty set.
Something unexpected occurred, when DELETE .. where is NULL , it returns 1 row affected.

as follows
```shell
mysql> select * from t1;
+------------+
| a          |
+------------+
| 0000-00-00 |
+------------+
1 row in set (0.00 sec)

mysql> select * from t1 where a is null;
Empty set (0.00 sec)

mysql> delete from t1 where a is null;
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
Empty set (0.00 sec)
```

### Expected behavior

when SQL (SELECT .. where is NULL)  returns an empty set,
the data should not be deleted by the SQL(DELETE .. where is NULL)

```shell
mysql> select * from t1 where a is null;
+------------+
| a          |
+------------+
| 0000-00-00 |
+------------+
1 row in set (0.00 sec)

mysql> delete from t1 where a is null;
Query OK, 1 row affected (0.01 sec)

```

### How To Reproduce

```sql
create table t1(a date not null);
insert ignore into t1 values (0);
select * from t1 where a is null;
delete from t1 where a is null;
```

### Environment

ubuntu@ubuntu:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

ubuntu@ubuntu:~$ /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld Ver 5.7.36_v1.0.1_beta_2-StoneDB for Linux on x86_64 (build-)
build information as follow:
Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
Branch name: stonedb-5.7-dev
Last commit ID: https://github.com/stoneatom/stonedb/commit/208f79d80bae1667d147e0713950317c9ca6c6b9
Last commit time: Date: Sat Sep 17 16:19:42 2022 +0800
Build time: Date: Fri Sep 23 14:14:27 CST 2022

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by konghaiya** [comment]
There is a problem with the query in tianmu, not the deletion
<img width="303" alt="image" src="https://user-images.githubusercontent.com/106147765/196619198-b73b46f7-5f8f-4ece-82ef-b27a87e593d3.png">
