### ISSUE TITLE
bug(StoneDB 8.0) :  duplicate 'lc-messages-dir' config item in my.cnf.sample file

### ISSUE THREAD

**Issue by lujiashun** [stoneatom/stonedb#688]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

in branch StoneDB-8.0-dev, my.cnf.sample in ./scripts directory.
there are two 'lc-messages-dir' config items.

```
port                            = 3306
basedir                         = YOUR_ABS_PATH/
character-sets-dir              = YOUR_ABS_PATH/share/charsets/
lc-messages-dir                 = YOUR_ABS_PATH/share/
plugin_dir                      = YOUR_ABS_PATH/lib/plugin/
tmpdir                          = YOUR_ABS_PATH/tmp/
socket                          = YOUR_ABS_PATH/tmp/mysql.sock
datadir                         = YOUR_ABS_PATH/data/
pid-file                        = YOUR_ABS_PATH/data/mysqld.pid
log-error                       = YOUR_ABS_PATH/log/mysqld.log
lc-messages-dir                 = YOUR_ABS_PATH/share/english/
```

### Expected behavior

Just one 'lc-messages-dir'.

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by RingsC** [comment]
adds a params :  "lc_messages" to my.cnf.

**Comment by hustjieke** [comment]
Impact both on branch 5.7 and 8.0.

**Comment by lujiashun** [comment]
ACK
