### ISSUE TITLE
feature: StoneDB install support CentOS Stream 8

### ISSUE THREAD

**Issue by xingguang2013** [stoneatom/stonedb#710]
**Is your feature request related to a problem? Please describe.**
My server operating system is CentOS Stream 8，I found the installation failed by referring to the [Centos 7.x](https://stonedb.io/zh/docs/getting-started/quick-deployment/quick-deployment-57) installation, When checking dependent files, The following information: 

```shell
[xxx@VM-16-16-centos bin]# ldd mysqld
	linux-vdso.so.1 (0x00007ffd1f5cb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7d04d22000)
	libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00007f7d04b17000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f7d04906000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f7d046e9000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f7d04445000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f7d0421c000)
	libssl.so.10 => not found
	libcrypto.so.10 => not found
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7d04018000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7d03e10000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7d03a8e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7d036c9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d04f42000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7d03334000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7d0311c000)
[xxx@VM-16-16-centos bin]# ldd mysql
	linux-vdso.so.1 (0x00007fffa85ca000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3285436000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f328522e000)
	libssl.so.10 => not found
	libcrypto.so.10 => not found
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f328502a000)
	libncurses.so.5 => not found
	libtinfo.so.5 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007f3284ca8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f32848e3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3285656000)
```

Install missing dependent files [compile-using-centos7-57](https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-centos7/compile-using-centos7-57) The following information: 

```shell
[xxx@VM-16-16-centos bin]# gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The version does not meet the requirements. Switch gcc to the correct version, The following information(Wrong report): 

```shell
[xxx@VM-16-16-centos bin]# yum install centos-release-scl scl-utils-build -y
Last metadata expiration check: 3:59:41 ago on Wed 12 Oct 2022 01:54:02 PM CST.
No match for argument: centos-release-scl
Error: Unable to find a match: centos-release-scl

[xxx@VM-16-16-centos bin]# yum install devtoolset-9-gcc.x86_64 devtoolset-9-gcc-c++.x86_64 devtoolset-9-gcc-gdb-plugin.x86_64 -y
Last metadata expiration check: 4:01:39 ago on Wed 12 Oct 2022 01:54:02 PM CST.
No match for argument: devtoolset-9-gcc.x86_64
No match for argument: devtoolset-9-gcc-c++.x86_64
No match for argument: devtoolset-9-gcc-gdb-plugin.x86_64
Error: Unable to find a match: devtoolset-9-gcc.x86_64 devtoolset-9-gcc-c++.x86_64 devtoolset-9-gcc-gdb-plugin.x86_64
```
Unable to switch to version 9.3.0 due to the above errors

`The stonedb database cannot be installed for this reason`

**Describe the solution you'd like**
`Stonedb was successfully installed in CentOS Stream 8`

**Describe alternatives you've considered**
`none`

**Additional context**
`none`

**Comment by CodingSuen** [comment]
@xingguang2013 Hi xingguang2013, for compiling stonedb, there are some different steps between CentOS 7 and CentOS Stream 8.
I list them as below.
Let us know if you have any questions, thanks.

1. Install Dependencies
run below installations after running the first step from [compile-using-centos7-57](https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-centos7/compile-using-centos7-57)
yum install -y epel-release
yum install -y jemalloc
dnf config-manager --set-enabled powertools || true
yum install -y jemalloc-devel
yum install -y libedit-devel
yum install -y snappy-devel
yum install -y libtirpc-devel

2. Compile GCC 9.3
wget https://gcc.gnu.org/pub/gcc/releases/gcc-9.3.0/gcc-9.3.0.tar.gz
tar zxvf gcc-9.3.0.tar.gz
cd gcc-9.3.0/
./contrib/download_prerequisites
./configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
make -j`nproc`
make install -j`nproc`
reboot
gcc --version
g++ --version
c++ --version

3. Install make
wget http://mirrors.ustc.edu.cn/gnu/make/make-3.82.tar.gz
tar -zxvf make-3.82.tar.gz
cd make-3.82
./configure  --prefix=/usr/local/make
Modify the file ./glob/glob.c , comment "#if ..." at line 211 and "endif" at line 232
`//#if !defined __alloca && !defined __GNU_LIBRARY__`
`//#endif`
make -j`nproc`
make install -j`nproc`
rm -rf /usr/local/bin/make
ln -s /usr/local/make/bin/make /usr/local/bin/make
mv /usr/bin/make /usr/bin/make.bak
ln -s /usr/local/make/bin/make /usr/bin/make
make --version

4. Install rpcsvc-proto
wget https://github.com/thkukuk/rpcsvc-proto/releases/download/v1.4/rpcsvc-proto-1.4.tar.gz
tar -zxvf rpcsvc-proto-1.4.tar.gz
cd rpcsvc-proto-1.4/
./configure
make -j`nproc`
make install -j`nproc`
