### ISSUE TITLE
feature(StoneDB 8.0): add some mtr test case

### ISSUE THREAD

**Issue by lujiashun** [stoneatom/stonedb#723]
**Is your feature request related to a problem? Please describe.**

port some test case from 5.7 to 8.0:
    ./suite/tianmu/t/alter_table_v1.test
    ./suite/tianmu/t/issue364..test 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lujiashun** [comment]
1 insert dml events is not stored immediately into binlog file in  this format "insert  into ....",  it will be delayed into the binlog with other insert dml events in that format "load into outfile...";
2 binlog warning should not be reported, because the data is recorded in the loaded-in file;

**Comment by RingsC** [comment]
> 1 insert dml events is not stored immediately into binlog file in this format "insert into ....", it will be delayed into the binlog with other insert dml events in that format "load into outfile..."; 2 binlog warning should not be reported, because the data is recorded in the loaded-in file;

I think convert the insert bin log event into load into outfile is not a proper approach, we should re-implement in future.
