### ISSUE TITLE
bug: select * from t1 where 1=1 and 1=1 or b>2;The query result is empty

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#733]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
CREATE TABLE t1 (a INT NOT NULL, b INT)engine=tianmu;
INSERT INTO t1 VALUES (1, 1),(1,2),(1,3);
select * from t1 where 1=1 and 1=1 or b>2;

##The error results are as follows
Empty set (0.01 sec)
```

### Expected behavior

```
select * from t1 where 1=1 and 1=1 or b>2;
+---+------+
| a | b    |
+---+------+
| 1 |    1 |
| 1 |    2 |
| 1 |    3 |
+---+------+
```

### How To Reproduce

```
CREATE TABLE t1 (a INT NOT NULL, b INT)engine=tianmu;
INSERT INTO t1 VALUES (1, 1),(1,2),(1,3);
select * from t1 where 1=1 and 1=1 or b>2;
```

### Environment

Ver 14.14 Distrib 5.7.36-StoneDB, for Linux (x86_64) using  EditLine wrapper

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
mysql> select * from t1 where (a=a and 1=1 and 1=1)  or b>1;
ERROR 6 (HY000): The query includes syntax that is not supported by the storage engine. Either restructure the query with supported syntax, or enable the MySQL core::Query Path in config file to execute the query with reduced performance.
