### ISSUE TITLE
bug: Failed to back up data using mysqldump

### ISSUE THREAD

**Issue by quanjin9099** [stoneatom/stonedb#734]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

stonedb57/install/bin/mysqldump  -uroot -p***** -P3306 --skip-opt --master-data=2 --single-transaction --set-gtid-purged=off  --databases dumpdb > /tmp/dumpdb.sql   
使用这个命令备份数据库的时候,返回错误: 
mysqldump: Error: Binlogging on server not active

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by zsp108** [comment]
set log_bin=ON,
or 
```shell
stonedb57/install/bin/mysqldump -uroot -p***** -P3306 --skip-opt --single-transaction --set-gtid-purged=off  -databases dumpdb > /tmp/dumpdb.sql
```

**Comment by Nliver** [comment]
Check the parameter file to see whether binlog is enabled correctly. 
`log_bin=/xxx` is correct

**Comment by Nliver** [comment]
Hi~ Have you solved the problem? @quanjin9099

**Comment by quanjin9099** [comment]
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: [ERROR] mysqldump: unknown option '-b'

**Comment by quanjin9099** [comment]
cat /stonedb57/install/my.cnf
[mysqld]
port      = 3306
socket    = /stonedb57/install/tmp/mysql.sock
basedir   = /stonedb57/install
datadir   = /stonedb57/install/data
pid_file  = /stonedb57/install/data/mysqld.pid
log_error = /stonedb57/install/log/mysqld.log
innodb_log_group_home_dir   = /stonedb57/install/redolog/
innodb_undo_directory       = /stonedb57/install/undolog/

**Comment by quanjin9099** [comment]
按照 https://stonedb.io/zh/docs/getting-started/quick-deployment/quick-deployment-57 
指导部署的数据库

**Comment by quanjin9099** [comment]
@Nliver

**Comment by Nliver** [comment]
ysqldump: [ERROR] mysqldump: unknown option '-b'
--->
If you want to dump a database,you can use “--database” or “-B”.For example
mysqldump -u username -p xxx -h xxx --single-transaction -B dbname > /xxx.sql

@quanjin9099

**Comment by Nliver** [comment]
I noticed that you have opened a new issue #849，so this issue will be closed.
