### ISSUE TITLE
bug: make:error: 'kPathNotFound' is not a member of 'rocksdb::Statu'.....

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#76]
**Describe the problem**

`[ 61%] Building CXX object storage/stonedb/CMakeFiles/stonedb.dir/index/kv_store.cpp.o
/home/stonedb/storage/stonedb/index/kv_store.cpp: In member function 'void stonedb::index::KVStore::Init()':
/home/stonedb/storage/stonedb/index/kv_store.cpp:48:110: error: 'kPathNotFound' is not a member of 'rocksdb::Statu'
 !status.ok() && ((status.subcode() == rocksdb::Status::kNone) || (status.subcode() == rocksdb::Status::kPathNotFound)) )
                                                                                                        ^~~~~~~~~~~~~
make[2]: *** [storage/stonedb/CMakeFiles/stonedb.dir/index/kv_store.cpp.o] Error 1
make[1]: *** [storage/stonedb/CMakeFiles/stonedb.dir/all] Error 2
make: *** [all] Error 2
[1]+  Exit 2                  make`
**Expected behavior**

no error,make success
**How To Reproduce**

please see：https://stoneatom.yuque.com/staff-ft8n1u/dghuxr/ro7qqw
**Environment**

ubuntu 20.4
**Additional context**

no

**Comment by shangyanwen** [comment]
【resolve】Re-updating the dependency library solves the problem

**Comment by RingsC** [comment]
See the PR: #69 , and have fixed it.
