### ISSUE TITLE
bug: A master-slave replication,The insertion delay nature of StoneDB causes the replication thread to miss the record

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#847]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
StoneDB's insert delay nature causes the replication thread to be unable to find the record, which in turn affects performance if the insert delay is turned off
```

### Expected behavior

```
The insertion delay does not affect the functions associated with master/slave replication
```

### How To Reproduce

stonedb test master/slave synchronization

#notes：stonedb internal testing, please contact guanhaitao for questions

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by wisehead** [comment]
@duanfuxiang0 will fix it in next release
