### ISSUE TITLE
bug: Failed to back up data using mysqldump

### ISSUE THREAD

**Issue by quanjin9099** [stoneatom/stonedb#849]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

https://github.com/stoneatom/stonedb/issues/734

### Expected behavior

https://github.com/stoneatom/stonedb/issues/734

### How To Reproduce

https://github.com/stoneatom/stonedb/issues/734

### Environment

https://github.com/stoneatom/stonedb/issues/734

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by haitaoguan** [comment]
mysqldump: [ERROR] mysqldump: unknown option '-b' 
--->
If you want to dump a database,you can use “--database” or “-B”.For example
mysqldump -u username -p xxx -h xxx --single-transaction -B dbname > /xxx.sql

**Comment by RingsC** [comment]
We will close it now, and fee freel to reopen it again. Thanks.
