### ISSUE TITLE
bug:mysql5.6ERROR 2013 (HY000): Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by LuiciferYi** [stoneatom/stonedb#86]
+-------+-------------+------+-----+---------+----------------+
| Field | Type        | Null | Key | Default | Extra          |
+-------+-------------+------+-----+---------+----------------+
| uid   | int(11)     | NO   | PRI | NULL    | auto_increment |
| uname | varchar(20) | NO   |     | NULL    |                |
| age   | int(11)     | YES  |     | NULL    |                |
| sex   | varchar(2)  | YES  |     | NULL    |                |
+-------+-------------+------+-----+---------+----------------+
4 rows in set (0.01 sec)
mysql> ALTER TABLE user CHANGE uname name VARCHAR(21) NOT NULL;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by haitaoguan** [comment]
This Bug was fixed in the 5.6 release
@hustjieke

**Comment by hustjieke** [comment]
Duplicate with #87

**Comment by LuiciferYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
