### ISSUE TITLE
bug: mysql 5.6ERROR 2013 (HY000): Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by LuiciferYi** [StoneAtom/stonedb#87]
+-------+-------------+------+-----+---------+----------------+
| Field | Type        | Null | Key | Default | Extra          |
+-------+-------------+------+-----+---------+----------------+
| uid   | int(11)     | NO   | PRI | NULL    | auto_increment |
| uname | varchar(20) | NO   |     | NULL    |                |
| age   | int(11)     | YES  |     | NULL    |                |
| sex   | varchar(2)  | YES  |     | NULL    |                |

ALTER TABLE user MODIFY uname VARCHAR(20);
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by haitaoguan** [comment]
This Bug was fixed in the 5.6 release.
@hustjieke

**Comment by hustjieke** [comment]
> This Bug was fixed in the 5.6 release. @hustjieke

Make sense.
