### ISSUE TITLE
feature: The limitation of all params of stonedb

### ISSUE THREAD

**Issue by RingsC** [stoneatom/stonedb#942]
**Is your feature request related to a problem? Please describe.**

To figure out all the params' boundary of stonedb.  and post to stonedb official homepage. such as, 
1: The data size we supported
2: The SQL syntax we supported by now. 
3: etc....

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nliver** [comment]
About the limits of relevant documents, has been updated in the website, please refer to this link: https://stonedb.io/docs/about-stonedb/limits  
then, I will close the issue
