### ISSUE TITLE
feature: To support Binlog in mandatory tianmu engine mode.

### ISSUE THREAD

**Issue by RingsC** [stoneatom/stonedb#956]
**Is your feature request related to a problem? Please describe.**

For some secnarios, we create table on primary node with `engine=innodb`, the a table with innodb engine will be create on secondary node, usually, stonedb. 
But, stonedb is a column-based storage engine. if we use stonedb and innodb table to do analytical processing, that make stonedb can not use its advantage. Therefore, we want to support a `MANDATORY_TIANMU` sql_mode to make sure the table created on stonedb is tianmu table.

syntax: 
```
set global sql_mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,MANDATORY_TIANMU';
```
when `MANDATORY_TIANMU` is set, the table created on stonedb will always create the tables as `tianmu` tables whether the primary node create table options is innodb table or not.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RingsC** [comment]
Function: 
  To make sure we create the table on stonedb is  a `tianmu` table mandatorily. 

Scope：Globally
Effect timing：When it was set, then it takes effect immediately.

How to configure：
● by sql client.
  ○ example：
mysql>set global sql_mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,**MANDATORY_TIANMU**';

● my.cnf 
  ○ example：
[mysqld] 
sql_mode        =  'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,**MANDATORY_TIANMU**'

default_storage_engine ：
default_storage_engine：same as MySQL, refer to MySQL document.

Others：
sql_mode ='MANDATORY_TIANMU' **>** default_storage_engine

**Comment by konghaiya** [comment]
ACK

**Comment by konghaiya** [comment]
The function of forcing the replacement engine to be tianmu only takes effect in the slave library
Step 1: First, you need to determine whether it is a slave database. This can be determined by whether (thread ->slave_thread) is true
According to the configuration of forced replacement: (sql_mode='MANDATORY_TIANMU ') and (default_storage_engine=tianmu)
Step 2: Determine whether the (sql_mode) and default engine are tianmu, and add (MANDATORY_TIANMU) this (sql_mode)
The above conditions can be judged in (mysql_execute_command)
