### ISSUE TITLE
bug: Existing 'test' Database

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#96]
**Describe the problem**

`Removing unutilized components will eliminate an attacker's ability to use them,Checks if 'test' database exists.`

**Expected behavior**

`No  default test database，Remove test database`

**How To Reproduce**

- Successfully installed and deployed database
- show databases；

**Environment**

**Additional context**

**Comment by haitaoguan** [comment]
StoneDB has been created a database named Test。It's not a bug。
@hustjieke
