### ISSUE TITLE
bug: INSERT INTO table error, but some data can be inserted successfully

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#965]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

When the INSERT INTO statement error, but unexpected some data can be inserted successfully.
All data should not be inserted into the table.

```shell
mysql> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (1), ('a');
ERROR 1366 (HY000): Incorrect integer value: 'a' for column 'a' at row 2

mysql> select * from t;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

```

### Expected behavior

```shell
mysql> create table t (a int);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values (1), ('a');
ERROR 1366 (HY000): Incorrect integer value: 'a' for column 'a' at row 2

mysql> select * from t;
Empty set (0.00 sec)
```

### How To Reproduce

```sql
drop table if exists t;
create table t (a int);
insert into t values (1), ('a');
select * from t;
```

### Environment

```shell
root@localhost:/# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: d0c2e01b6
        Last commit time: Date:   Wed Nov 2 19:58:00 2022 +0800
        Build time: Date: Sun 06 Nov 2022 08:50:06 AM UTC
root@ub01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by haitaoguan** [comment]
The tianmu engine not support transaction

**Comment by davidshiz** [comment]
It is recommended to give users a warning message that transactions are not supported, so as not to mislead users into thinking that all data has not been written,  but in fact some data has been inserted successfully

**Comment by adofsauron** [comment]
Turn off the insert buffer and try again

**Comment by isredstar** [comment]
@davidshiz When the tianmu_insert_delayed parameter is off，the question will be resolved. 
```
mysql> select * from t_insert;
+------+
| a    |
+------+
|    1 |
|    1 |
|    1 |
+------+
3 rows in set (0.00 sec)

mysql> insert into t_insert values (1), ('a');
ERROR 1366 (HY000): Incorrect integer value: 'a' for column 'a' at row 2
mysql> select * from t_insert;
+------+
| a    |
+------+
|    1 |
|    1 |
|    1 |
+------+
3 rows in set (0.00 sec)
```

**Comment by wisehead** [comment]
I close it for now, looks like its related to  tianmu_insert_delayed parameter.
