### ISSUE TITLE
bug: Scuba: have_symlink Option Set to YES

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#97]
**Describe the problem**

![image](https://user-images.githubusercontent.com/107781103/175474007-a25e8cdc-be2d-49c5-96f6-76e3df0ad355.png)

**Expected behavior**

`Verify value is "DISABLED"`
**How To Reproduce**

**Environment**

**Additional context**

**Comment by RingsC** [comment]
Pls, See the comment below:
[have_symlink:](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_have_symlink)

YES if symbolic link support is enabled, NO if not. This is required on Unix for support of the DATA DIRECTORY and INDEX DIRECTORY table options. If the server is started with the [--skip-symbolic-links](https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_symbolic-links) option, the value is DISABLED.

**Comment by shangyanwen** [comment]
Modifying parameters from the configuration is not a problem
