### ISSUE TITLE
question: When the Stonedb client terminal does not operate for a long time, Server has gone away

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#976]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

When the Stonedb client terminal does not operate for a long time, MySQL server has gone away
as follows

```shell
mysql> DROP DATABASE mcs119_db;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    6521
Current database: mcs119_db

Query OK, 1 row affected (0.02 sec)
```

### Environment

```shell
root@localhost:/# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: d0c2e01b6
        Last commit time: Date:   Wed Nov 2 19:58:00 2022 +0800
        Build time: Date: Sun 06 Nov 2022 08:50:06 AM UTC
root@ub01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by haitaoguan** [comment]
If the client does not interact with the server for a long time, the client will be automatically disconnected when the threshold of wait_timeout or interactive_timeout is reached
